// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ClassID    uuid.UUID
	TutorID    uuid.UUID
	Name       string
	RecordedAt time.Time
	UpdatedAt  time.Time
}

type ConsumerFailure struct {
	ConsumerName      string
	SourceTopic       string
	SourcePartition   int32
	SourceOffset      int64
	EventID           pgtype.UUID
	TutorID           pgtype.UUID
	FailureCategory   string
	FailedAt          time.Time
	ResolvedAt        pgtype.Timestamptz
	Resolution        pgtype.Text
	ResolutionCode    pgtype.Text
	ResolvedBy        pgtype.Text
	RepairReference   pgtype.Text
	ResolutionHistory []byte
}

type ConsumerReadiness struct {
	ConsumerName         string
	ProjectionGeneration uuid.UUID
	State                string
	UpdatedAt            time.Time
}

type ConsumerReplayManifest struct {
	ConsumerName         string
	ProjectionGeneration uuid.UUID
	SourceTopic          string
	TopicIdentity        string
	PartitionSet         []byte
	EarliestOffsets      []byte
	CapturedEndOffsets   []byte
	CompletedOffsets     []byte
	StartedAt            time.Time
	CompletedAt          pgtype.Timestamptz
	OperatorIdentity     string
}

type DigestRun struct {
	TutorID   uuid.UUID
	LocalDate pgtype.Date
	State     string
	Attempts  int32
	LastError string
	SentAt    pgtype.Timestamptz
	CreatedAt time.Time
	UpdatedAt time.Time
}

type HandledEvent struct {
	ConsumerName string
	EventID      uuid.UUID
	HandledAt    time.Time
}

type Outbox struct {
	ID           int64
	EventID      uuid.UUID
	EventName    string
	EventVersion int32
	OccurredAt   time.Time
	TutorID      uuid.UUID
	KeyKind      string
	KeyValue     uuid.UUID
	RequestID    string
	Topic        string
	Envelope     []byte
	CreatedAt    time.Time
	PublishedAt  pgtype.Timestamptz
}

type Recipient struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	RecordedAt  time.Time
	UpdatedAt   time.Time
}

type RosterPeriod struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
	EffectiveTo   pgtype.Date
	RecordedAt    time.Time
	UpdatedAt     time.Time
}

type Session struct {
	SessionID   uuid.UUID
	ClassID     uuid.UUID
	TutorID     uuid.UUID
	StartsAt    time.Time
	EndsAt      time.Time
	LocalDate   pgtype.Date
	CancelledAt pgtype.Timestamptz
	RecordedAt  time.Time
	UpdatedAt   time.Time
}
