// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloseRosterPeriod(ctx context.Context, arg CloseRosterPeriodParams) error
	GetDigestRun(ctx context.Context, arg GetDigestRunParams) (DigestRun, error)
	GetRecipient(ctx context.Context, tutorID uuid.UUID) (Recipient, error)
	// ------------------------------------------------------- authoritative record
	// InsertDigestRun is the scheduler's claim on one tutor's morning. The primary
	// key is the lock: a repeated tick is a unique violation rather than a second
	// email, which is what makes one digest per tutor per day true (STK-23).
	InsertDigestRun(ctx context.Context, arg InsertDigestRunParams) (DigestRun, error)
	// ListDigestSessions is the whole digest read: the tutor's sessions on their own
	// local day, the class label, and how many students were in that class on that
	// day. The count is counted here rather than stored, because an integer bumped up
	// and down is the accumulate in arrival order shape INV-7 forbids: a redelivery
	// would double count and a replay would multiply it (AC-9). Membership uses the
	// one coverage predicate spec 0003 states for all three services, inclusive at
	// both ends, so this and billing's ListBillableSessions can never disagree about
	// who was in a class on a day.
	ListDigestSessions(ctx context.Context, arg ListDigestSessionsParams) ([]ListDigestSessionsRow, error)
	MarkSessionCancelled(ctx context.Context, arg MarkSessionCancelledParams) error
	OpenRosterPeriod(ctx context.Context, arg OpenRosterPeriodParams) error
	// Hand written SQL for the daily digest, compiled to typed Go by sqlc (STK-3).
	//
	// Every statement names tutor_id (INV-8, AC-4). The projection upserts above the
	// line are run only by internal/consumer, on the identifying key the event
	// already carries, so a redelivery and a full replay both change nothing the
	// second time (AC-7). digest_runs below the line is the scheduler's own record
	// and no consumer writes it.
	// ---------------------------------------------------------------- projections
	UpsertClass(ctx context.Context, arg UpsertClassParams) error
	UpsertRecipient(ctx context.Context, arg UpsertRecipientParams) error
	// UpsertSession serves teaching.session.scheduled and teaching.session.moved
	// alike: a move is the same three columns at new values.
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
}

var _ Querier = (*Queries)(nil)
