// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipients.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getRecipient = `-- name: GetRecipient :one
SELECT tutor_id, email, display_name, timezone, language, recorded_at, updated_at
FROM recipients
WHERE tutor_id = $1
`

func (q *Queries) GetRecipient(ctx context.Context, tutorID uuid.UUID) (Recipient, error) {
	row := q.db.QueryRow(ctx, getRecipient, tutorID)
	var i Recipient
	err := row.Scan(
		&i.TutorID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.Language,
		&i.RecordedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRecipient = `-- name: UpsertRecipient :exec
INSERT INTO recipients (tutor_id, email, display_name, timezone, language)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tutor_id) DO UPDATE
SET email        = excluded.email,
    display_name = excluded.display_name,
    timezone     = excluded.timezone,
    language     = excluded.language,
    updated_at   = now()
`

type UpsertRecipientParams struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
}

func (q *Queries) UpsertRecipient(ctx context.Context, arg UpsertRecipientParams) error {
	_, err := q.db.Exec(ctx, upsertRecipient,
		arg.TutorID,
		arg.Email,
		arg.DisplayName,
		arg.Timezone,
		arg.Language,
	)
	return err
}
