// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AttendanceSheetIneligibleReason.
const (
	AttendanceSheetIneligibleReasonCancelled     AttendanceSheetIneligibleReason = "cancelled"
	AttendanceSheetIneligibleReasonClassArchived AttendanceSheetIneligibleReason = "class_archived"
	AttendanceSheetIneligibleReasonLessThannil   AttendanceSheetIneligibleReason = "<nil>"
	AttendanceSheetIneligibleReasonNotStarted    AttendanceSheetIneligibleReason = "not_started"
	AttendanceSheetIneligibleReasonReplaced      AttendanceSheetIneligibleReason = "replaced"
)

// Valid indicates whether the value is a known member of the AttendanceSheetIneligibleReason enum.
func (e AttendanceSheetIneligibleReason) Valid() bool {
	switch e {
	case AttendanceSheetIneligibleReasonCancelled:
		return true
	case AttendanceSheetIneligibleReasonClassArchived:
		return true
	case AttendanceSheetIneligibleReasonLessThannil:
		return true
	case AttendanceSheetIneligibleReasonNotStarted:
		return true
	case AttendanceSheetIneligibleReasonReplaced:
		return true
	default:
		return false
	}
}

// Defines values for AttendanceState.
const (
	Absent  AttendanceState = "Absent"
	Present AttendanceState = "Present"
)

// Valid indicates whether the value is a known member of the AttendanceState enum.
func (e AttendanceState) Valid() bool {
	switch e {
	case Absent:
		return true
	case Present:
		return true
	default:
		return false
	}
}

// Defines values for BillingProjectionState.
const (
	BillingProjectionStateActive  BillingProjectionState = "active"
	BillingProjectionStateWaiting BillingProjectionState = "waiting"
)

// Valid indicates whether the value is a known member of the BillingProjectionState enum.
func (e BillingProjectionState) Valid() bool {
	switch e {
	case BillingProjectionStateActive:
		return true
	case BillingProjectionStateWaiting:
		return true
	default:
		return false
	}
}

// Defines values for ClassCurrency.
const (
	VND ClassCurrency = "VND"
)

// Valid indicates whether the value is a known member of the ClassCurrency enum.
func (e ClassCurrency) Valid() bool {
	switch e {
	case VND:
		return true
	default:
		return false
	}
}

// Defines values for ClassColor.
const (
	Blue   ClassColor = "blue"
	Green  ClassColor = "green"
	Orange ClassColor = "orange"
	Red    ClassColor = "red"
	Rose   ClassColor = "rose"
	Violet ClassColor = "violet"
	Yellow ClassColor = "yellow"
)

// Valid indicates whether the value is a known member of the ClassColor enum.
func (e ClassColor) Valid() bool {
	switch e {
	case Blue:
		return true
	case Green:
		return true
	case Orange:
		return true
	case Red:
		return true
	case Rose:
		return true
	case Violet:
		return true
	case Yellow:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleRuleState.
const (
	ScheduleRuleStateActive    ScheduleRuleState = "active"
	ScheduleRuleStateCompleted ScheduleRuleState = "completed"
	ScheduleRuleStateEnded     ScheduleRuleState = "ended"
	ScheduleRuleStatePlanned   ScheduleRuleState = "planned"
	ScheduleRuleStateReplaced  ScheduleRuleState = "replaced"
	ScheduleRuleStateRetired   ScheduleRuleState = "retired"
)

// Valid indicates whether the value is a known member of the ScheduleRuleState enum.
func (e ScheduleRuleState) Valid() bool {
	switch e {
	case ScheduleRuleStateActive:
		return true
	case ScheduleRuleStateCompleted:
		return true
	case ScheduleRuleStateEnded:
		return true
	case ScheduleRuleStatePlanned:
		return true
	case ScheduleRuleStateReplaced:
		return true
	case ScheduleRuleStateRetired:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleSessionState.
const (
	ScheduleSessionStateActive    ScheduleSessionState = "active"
	ScheduleSessionStateCancelled ScheduleSessionState = "cancelled"
	ScheduleSessionStateReplaced  ScheduleSessionState = "replaced"
)

// Valid indicates whether the value is a known member of the ScheduleSessionState enum.
func (e ScheduleSessionState) Valid() bool {
	switch e {
	case ScheduleSessionStateActive:
		return true
	case ScheduleSessionStateCancelled:
		return true
	case ScheduleSessionStateReplaced:
		return true
	default:
		return false
	}
}

// Defines values for SessionNotEligibleDetailsReason.
const (
	SessionNotEligibleDetailsReasonCancelled     SessionNotEligibleDetailsReason = "cancelled"
	SessionNotEligibleDetailsReasonClassArchived SessionNotEligibleDetailsReason = "class_archived"
	SessionNotEligibleDetailsReasonNotStarted    SessionNotEligibleDetailsReason = "not_started"
	SessionNotEligibleDetailsReasonReplaced      SessionNotEligibleDetailsReason = "replaced"
)

// Valid indicates whether the value is a known member of the SessionNotEligibleDetailsReason enum.
func (e SessionNotEligibleDetailsReason) Valid() bool {
	switch e {
	case SessionNotEligibleDetailsReasonCancelled:
		return true
	case SessionNotEligibleDetailsReasonClassArchived:
		return true
	case SessionNotEligibleDetailsReasonNotStarted:
		return true
	case SessionNotEligibleDetailsReasonReplaced:
		return true
	default:
		return false
	}
}

// Defines values for SessionSummaryState.
const (
	SessionSummaryStateActive        SessionSummaryState = "active"
	SessionSummaryStateCancelled     SessionSummaryState = "cancelled"
	SessionSummaryStateClassArchived SessionSummaryState = "class_archived"
	SessionSummaryStateReplaced      SessionSummaryState = "replaced"
)

// Valid indicates whether the value is a known member of the SessionSummaryState enum.
func (e SessionSummaryState) Valid() bool {
	switch e {
	case SessionSummaryStateActive:
		return true
	case SessionSummaryStateCancelled:
		return true
	case SessionSummaryStateClassArchived:
		return true
	case SessionSummaryStateReplaced:
		return true
	default:
		return false
	}
}

// Defines values for TutorLanguage.
const (
	TutorLanguageEn TutorLanguage = "en"
	TutorLanguageVi TutorLanguage = "vi"
)

// Valid indicates whether the value is a known member of the TutorLanguage enum.
func (e TutorLanguage) Valid() bool {
	switch e {
	case TutorLanguageEn:
		return true
	case TutorLanguageVi:
		return true
	default:
		return false
	}
}

// Defines values for StartGoogleSignInParamsLang.
const (
	StartGoogleSignInParamsLangEn StartGoogleSignInParamsLang = "en"
	StartGoogleSignInParamsLangVi StartGoogleSignInParamsLang = "vi"
)

// Valid indicates whether the value is a known member of the StartGoogleSignInParamsLang enum.
func (e StartGoogleSignInParamsLang) Valid() bool {
	switch e {
	case StartGoogleSignInParamsLangEn:
		return true
	case StartGoogleSignInParamsLangVi:
		return true
	default:
		return false
	}
}

// ActiveMembershipDetails defines model for ActiveMembershipDetails.
type ActiveMembershipDetails struct {
	Classes []ClassReference `json:"classes"`
}

// AttendanceChangedDetails defines model for AttendanceChangedDetails.
type AttendanceChangedDetails struct {
	Sheet AttendanceSheet `json:"sheet"`
}

// AttendanceMarkInput defines model for AttendanceMarkInput.
type AttendanceMarkInput struct {
	State     AttendanceState    `json:"state"`
	StudentId openapi_types.UUID `json:"student_id"`
}

// AttendanceSave defines model for AttendanceSave.
type AttendanceSave struct {
	MarkedAt  time.Time             `json:"marked_at"`
	Marks     []SavedAttendanceMark `json:"marks"`
	SessionId openapi_types.UUID    `json:"session_id"`
}

// AttendanceSheet defines model for AttendanceSheet.
type AttendanceSheet struct {
	Eligible         bool                             `json:"eligible"`
	IneligibleReason *AttendanceSheetIneligibleReason `json:"ineligible_reason"`
	Revision         string                           `json:"revision"`
	Session          SessionSummary                   `json:"session"`
	Students         []AttendanceStudent              `json:"students"`
}

// AttendanceSheetIneligibleReason defines model for AttendanceSheet.IneligibleReason.
type AttendanceSheetIneligibleReason string

// AttendanceState defines model for AttendanceState.
type AttendanceState string

// AttendanceStudent defines model for AttendanceStudent.
type AttendanceStudent struct {
	Archived  bool               `json:"archived"`
	MarkedAt  *time.Time         `json:"marked_at"`
	Name      string             `json:"name"`
	State     *AttendanceState   `json:"state"`
	StudentId openapi_types.UUID `json:"student_id"`
}

// BillingProjection defines model for BillingProjection.
type BillingProjection struct {
	AttendanceCount int64                  `json:"attendance_count"`
	ClassCount      int64                  `json:"class_count"`
	LatestUpdatedAt *time.Time             `json:"latest_updated_at"`
	OpenRosterCount int64                  `json:"open_roster_count"`
	SessionCount    int64                  `json:"session_count"`
	State           BillingProjectionState `json:"state"`
	StudentCount    int64                  `json:"student_count"`
}

// BillingProjectionState defines model for BillingProjection.State.
type BillingProjectionState string

// CanonicalSession defines model for CanonicalSession.
type CanonicalSession struct {
	CancelledAt     *time.Time           `json:"cancelled_at"`
	ClassId         openapi_types.UUID   `json:"class_id"`
	DisplayTimeZone string               `json:"display_time_zone"`
	EndUtcOffset    string               `json:"end_utc_offset"`
	EndsAt          time.Time            `json:"ends_at"`
	LocalDate       openapi_types.Date   `json:"local_date"`
	MovedAt         *time.Time           `json:"moved_at"`
	OriginLocalDate openapi_types.Date   `json:"origin_local_date"`
	ScheduleRuleId  *openapi_types.UUID  `json:"schedule_rule_id"`
	SessionId       openapi_types.UUID   `json:"session_id"`
	SourceTimeZone  *string              `json:"source_time_zone"`
	StartUtcOffset  string               `json:"start_utc_offset"`
	StartsAt        time.Time            `json:"starts_at"`
	State           ScheduleSessionState `json:"state"`
	SupersededAt    *time.Time           `json:"superseded_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
	Version         int64                `json:"version"`
}

// ChangeRosterRequest defines model for ChangeRosterRequest.
type ChangeRosterRequest struct {
	Additions  []openapi_types.UUID `json:"additions"`
	ChangeDate openapi_types.Date   `json:"change_date"`
	Removals   []openapi_types.UUID `json:"removals"`
}

// Class defines model for Class.
type Class struct {
	ClassId           openapi_types.UUID `json:"class_id"`
	Color             ClassColor         `json:"color"`
	Currency          ClassCurrency      `json:"currency"`
	Name              string             `json:"name"`
	RateAmount        int64              `json:"rate_amount"`
	RateEffectiveFrom openapi_types.Date `json:"rate_effective_from"`
	ScheduleRevision  int64              `json:"schedule_revision"`
}

// ClassCurrency defines model for Class.Currency.
type ClassCurrency string

// ClassColor defines model for ClassColor.
type ClassColor string

// ClassReference defines model for ClassReference.
type ClassReference struct {
	ClassId openapi_types.UUID `json:"class_id"`
	Name    string             `json:"name"`
}

// ClassRoster defines model for ClassRoster.
type ClassRoster struct {
	Class        ClassSummary       `json:"class"`
	ResolvedDate openapi_types.Date `json:"resolved_date"`
	Students     []RosterStudent    `json:"students"`
}

// ClassSummary defines model for ClassSummary.
type ClassSummary struct {
	ClassId openapi_types.UUID `json:"class_id"`
	Color   ClassColor         `json:"color"`
	Name    string             `json:"name"`
}

// CreateClassRequest Exactly one of first_session or schedule is required.
type CreateClassRequest struct {
	Color        *ClassColor          `json:"color,omitempty"`
	FirstSession *FirstSessionInput   `json:"first_session,omitempty"`
	Name         string               `json:"name"`
	RateAmount   int64                `json:"rate_amount"`
	Schedule     *WeeklyScheduleInput `json:"schedule,omitempty"`
}

// CreateClassResponse defines model for CreateClassResponse.
type CreateClassResponse struct {
	AdoptedCount   int                  `json:"adopted_count"`
	CandidateCount int                  `json:"candidate_count"`
	Class          Class                `json:"class"`
	CreatedCount   int                  `json:"created_count"`
	FirstSession   *TeachingSession     `json:"first_session"`
	Rule           *ScheduleRuleSummary `json:"rule"`
}

// CreateStudentRequest defines model for CreateStudentRequest.
type CreateStudentRequest struct {
	Name  string  `json:"name"`
	Phone *string `json:"phone,omitempty"`
}

// EndScheduleRequest defines model for EndScheduleRequest.
type EndScheduleRequest struct {
	ExpectedRevision int64              `json:"expected_revision"`
	LastDate         openapi_types.Date `json:"last_date"`
}

// EndScheduleResponse defines model for EndScheduleResponse.
type EndScheduleResponse struct {
	Class           Class               `json:"class"`
	PreservedCount  int                 `json:"preserved_count"`
	Rule            ScheduleRuleSummary `json:"rule"`
	SupersededCount int                 `json:"superseded_count"`
}

// Error The one error shape at the gateway boundary (spec 0001).
type Error struct {
	Error struct {
		// Code Examples: invalid_input
		Code      string                  `json:"code"`
		Details   *map[string]interface{} `json:"details,omitempty"`
		Message   string                  `json:"message"`
		RequestId string                  `json:"request_id"`
	} `json:"error"`
}

// FirstSessionInput defines model for FirstSessionInput.
type FirstSessionInput struct {
	// EndTime Examples: 17:30
	EndTime   LocalTime          `json:"end_time"`
	LocalDate openapi_types.Date `json:"local_date"`

	// StartTime Examples: 17:30
	StartTime LocalTime `json:"start_time"`
}

// Health defines model for Health.
type Health struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

// Home defines model for Home.
type Home struct {
	BillingProjection            *BillingProjection `json:"billing_projection"`
	BillingProjectionUnavailable *string            `json:"billing_projection_unavailable"`
	LocalDate                    openapi_types.Date `json:"local_date"`
	NextCursor                   *string            `json:"next_cursor"`
	NextLocalMidnightAt          time.Time          `json:"next_local_midnight_at"`
	RequestTimeZone              string             `json:"request_time_zone"`
	Sessions                     []HomeSession      `json:"sessions"`
	SetupDefaults                SetupDefaults      `json:"setup_defaults"`
	Tutor                        Tutor              `json:"tutor"`
}

// HomeBillingProjection defines model for HomeBillingProjection.
type HomeBillingProjection struct {
	BillingProjection            *BillingProjection `json:"billing_projection"`
	BillingProjectionUnavailable *string            `json:"billing_projection_unavailable"`
}

// HomeSession defines model for HomeSession.
type HomeSession struct {
	ClassColor ClassColor         `json:"class_color"`
	ClassId    openapi_types.UUID `json:"class_id"`
	ClassName  string             `json:"class_name"`
	EndsAt     time.Time          `json:"ends_at"`
	LocalDate  openapi_types.Date `json:"local_date"`
	SessionId  openapi_types.UUID `json:"session_id"`
	StartsAt   time.Time          `json:"starts_at"`
	Students   []HomeStudent      `json:"students"`
}

// HomeStudent defines model for HomeStudent.
type HomeStudent struct {
	AttendanceState *AttendanceState   `json:"attendance_state"`
	MarkedAt        *time.Time         `json:"marked_at"`
	Name            string             `json:"name"`
	StudentId       openapi_types.UUID `json:"student_id"`
}

// LocalTime Examples: 17:30
type LocalTime = string

// MoveSessionRequest defines model for MoveSessionRequest.
type MoveSessionRequest struct {
	// EndTime Examples: 17:30
	EndTime         LocalTime          `json:"end_time"`
	ExpectedVersion int64              `json:"expected_version"`
	LocalDate       openapi_types.Date `json:"local_date"`

	// StartTime Examples: 17:30
	StartTime LocalTime `json:"start_time"`
}

// PutScheduleRequest defines model for PutScheduleRequest.
type PutScheduleRequest struct {
	EffectiveFrom    openapi_types.Date        `json:"effective_from"`
	ExpectedRevision int64                     `json:"expected_revision"`
	Slots            []WeeklyScheduleSlotInput `json:"slots"`
	ValidThrough     openapi_types.Date        `json:"valid_through"`
}

// PutScheduleResponse defines model for PutScheduleResponse.
type PutScheduleResponse struct {
	AdoptedCount    int                 `json:"adopted_count"`
	CandidateCount  int                 `json:"candidate_count"`
	Class           Class               `json:"class"`
	CreatedCount    int                 `json:"created_count"`
	FirstSession    *TeachingSession    `json:"first_session"`
	PreservedCount  int                 `json:"preserved_count"`
	Rule            ScheduleRuleSummary `json:"rule"`
	SupersededCount int                 `json:"superseded_count"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Checks  *map[string]string `json:"checks,omitempty"`
	Service string             `json:"service"`
	Status  string             `json:"status"`
}

// RosterConflictDetails defines model for RosterConflictDetails.
type RosterConflictDetails struct {
	Class        ClassSummary            `json:"class"`
	ResolvedDate openapi_types.Date      `json:"resolved_date"`
	Students     []RosterConflictStudent `json:"students"`
}

// RosterConflictStudent defines model for RosterConflictStudent.
type RosterConflictStudent struct {
	Archived      bool                `json:"archived"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to"`
	Name          string              `json:"name"`
	StudentId     openapi_types.UUID  `json:"student_id"`
}

// RosterStudent defines model for RosterStudent.
type RosterStudent struct {
	Archived      bool                `json:"archived"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to"`
	Name          string              `json:"name"`
	Phone         *string             `json:"phone"`
	StudentId     openapi_types.UUID  `json:"student_id"`
}

// SaveAttendanceRequest defines model for SaveAttendanceRequest.
type SaveAttendanceRequest struct {
	Marks    []AttendanceMarkInput `json:"marks"`
	Revision string                `json:"revision"`
}

// SavedAttendanceMark defines model for SavedAttendanceMark.
type SavedAttendanceMark struct {
	MarkedAt  time.Time          `json:"marked_at"`
	State     AttendanceState    `json:"state"`
	StudentId openapi_types.UUID `json:"student_id"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	Classes           []ScheduleClass       `json:"classes"`
	From              openapi_types.Date    `json:"from"`
	NextHistoryCursor *string               `json:"next_history_cursor"`
	ReplacedHistory   []ScheduleSession     `json:"replaced_history"`
	RequestTimeZone   string                `json:"request_time_zone"`
	Rules             []ScheduleRuleSummary `json:"rules"`
	Sessions          []ScheduleSession     `json:"sessions"`
	Through           openapi_types.Date    `json:"through"`
	TutorId           openapi_types.UUID    `json:"tutor_id"`
}

// ScheduleClass defines model for ScheduleClass.
type ScheduleClass struct {
	ClassId          openapi_types.UUID `json:"class_id"`
	Color            ClassColor         `json:"color"`
	Name             string             `json:"name"`
	ScheduleRevision int64              `json:"schedule_revision"`
}

// ScheduleRuleState defines model for ScheduleRuleState.
type ScheduleRuleState string

// ScheduleRuleSummary defines model for ScheduleRuleSummary.
type ScheduleRuleSummary struct {
	ClassId        openapi_types.UUID        `json:"class_id"`
	EndedAt        *time.Time                `json:"ended_at"`
	ReplacedAt     *time.Time                `json:"replaced_at"`
	RetiredAt      *time.Time                `json:"retired_at"`
	Revision       int64                     `json:"revision"`
	ScheduleRuleId openapi_types.UUID        `json:"schedule_rule_id"`
	Slots          []WeeklyScheduleSlotInput `json:"slots"`
	State          ScheduleRuleState         `json:"state"`
	TimeZone       string                    `json:"time_zone"`
	ValidFrom      openapi_types.Date        `json:"valid_from"`
	ValidThrough   openapi_types.Date        `json:"valid_through"`
}

// ScheduleSession defines model for ScheduleSession.
type ScheduleSession struct {
	CancelledAt   *time.Time         `json:"cancelled_at"`
	ClassArchived bool               `json:"class_archived"`
	ClassColor    ClassColor         `json:"class_color"`
	ClassId       openapi_types.UUID `json:"class_id"`
	ClassName     string             `json:"class_name"`
	DisplayDate   openapi_types.Date `json:"display_date"`

	// DisplayEnd Examples: 17:30
	DisplayEnd LocalTime `json:"display_end"`

	// DisplayStart Examples: 17:30
	DisplayStart    LocalTime            `json:"display_start"`
	EndUtcOffset    string               `json:"end_utc_offset"`
	EndsAt          time.Time            `json:"ends_at"`
	LocalDate       openapi_types.Date   `json:"local_date"`
	MovedAt         *time.Time           `json:"moved_at"`
	OriginLocalDate openapi_types.Date   `json:"origin_local_date"`
	ScheduleRuleId  *openapi_types.UUID  `json:"schedule_rule_id"`
	SessionId       openapi_types.UUID   `json:"session_id"`
	SourceTimeZone  *string              `json:"source_time_zone"`
	StartUtcOffset  string               `json:"start_utc_offset"`
	StartsAt        time.Time            `json:"starts_at"`
	State           ScheduleSessionState `json:"state"`
	SupersededAt    *time.Time           `json:"superseded_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
	Version         int64                `json:"version"`
}

// ScheduleSessionState defines model for ScheduleSessionState.
type ScheduleSessionState string

// Session What the browser holds after a refresh: an access token in memory only,
// and when it stops being valid. The refresh token itself is never in a
// body, only in the HttpOnly cookie beside it (spec 0004).
type Session struct {
	AccessExpiresAt time.Time `json:"access_expires_at"`
	AccessToken     string    `json:"access_token"`
}

// SessionNotEligibleDetails defines model for SessionNotEligibleDetails.
type SessionNotEligibleDetails struct {
	Reason SessionNotEligibleDetailsReason `json:"reason"`
}

// SessionNotEligibleDetailsReason defines model for SessionNotEligibleDetails.Reason.
type SessionNotEligibleDetailsReason string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	ClassColor ClassColor          `json:"class_color"`
	ClassId    openapi_types.UUID  `json:"class_id"`
	ClassName  string              `json:"class_name"`
	EndsAt     time.Time           `json:"ends_at"`
	LocalDate  openapi_types.Date  `json:"local_date"`
	SessionId  openapi_types.UUID  `json:"session_id"`
	StartsAt   time.Time           `json:"starts_at"`
	State      SessionSummaryState `json:"state"`
}

// SessionSummaryState defines model for SessionSummary.State.
type SessionSummaryState string

// SessionVersionRequest defines model for SessionVersionRequest.
type SessionVersionRequest struct {
	ExpectedVersion int64 `json:"expected_version"`
}

// SetupDefaults defines model for SetupDefaults.
type SetupDefaults struct {
	// EndTime Examples: 17:30
	EndTime   LocalTime          `json:"end_time"`
	LocalDate openapi_types.Date `json:"local_date"`

	// StartTime Examples: 17:30
	StartTime LocalTime `json:"start_time"`
}

// StudentChangedDetails defines model for StudentChangedDetails.
type StudentChangedDetails struct {
	StudentId openapi_types.UUID `json:"student_id"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// StudentDetail defines model for StudentDetail.
type StudentDetail struct {
	Memberships []StudentMembership `json:"memberships"`
	Student     StudentRecord       `json:"student"`
}

// StudentMembership defines model for StudentMembership.
type StudentMembership struct {
	Active        bool                `json:"active"`
	ClassColor    ClassColor          `json:"class_color"`
	ClassId       openapi_types.UUID  `json:"class_id"`
	ClassName     string              `json:"class_name"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to"`
}

// StudentPage defines model for StudentPage.
type StudentPage struct {
	NextCursor *string          `json:"next_cursor"`
	Students   []StudentSummary `json:"students"`
}

// StudentRecord defines model for StudentRecord.
type StudentRecord struct {
	CreatedAt time.Time          `json:"created_at"`
	Name      string             `json:"name"`
	Phone     *string            `json:"phone"`
	StudentId openapi_types.UUID `json:"student_id"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// StudentSummary defines model for StudentSummary.
type StudentSummary struct {
	ActiveClassCount int64              `json:"active_class_count"`
	Name             string             `json:"name"`
	Phone            *string            `json:"phone"`
	StudentId        openapi_types.UUID `json:"student_id"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

// TeachingHome defines model for TeachingHome.
type TeachingHome struct {
	LocalDate           openapi_types.Date `json:"local_date"`
	NextCursor          *string            `json:"next_cursor"`
	NextLocalMidnightAt time.Time          `json:"next_local_midnight_at"`
	RequestTimeZone     string             `json:"request_time_zone"`
	Sessions            []HomeSession      `json:"sessions"`
	SetupDefaults       SetupDefaults      `json:"setup_defaults"`
}

// TeachingSession defines model for TeachingSession.
type TeachingSession struct {
	ClassId   openapi_types.UUID `json:"class_id"`
	EndsAt    time.Time          `json:"ends_at"`
	LocalDate openapi_types.Date `json:"local_date"`
	SessionId openapi_types.UUID `json:"session_id"`
	StartsAt  time.Time          `json:"starts_at"`
}

// Tutor defines model for Tutor.
type Tutor struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Language    TutorLanguage       `json:"language"`
	Timezone    string              `json:"timezone"`
	TutorId     openapi_types.UUID  `json:"tutor_id"`
}

// TutorLanguage defines model for Tutor.Language.
type TutorLanguage string

// UpdateStudentRequest defines model for UpdateStudentRequest.
type UpdateStudentRequest struct {
	ExpectedUpdatedAt time.Time `json:"expected_updated_at"`
	Name              *string   `json:"name,omitempty"`
	Phone             *string   `json:"phone,omitempty"`
}

// WeeklyScheduleInput defines model for WeeklyScheduleInput.
type WeeklyScheduleInput struct {
	Slots        []WeeklyScheduleSlotInput `json:"slots"`
	ValidFrom    openapi_types.Date        `json:"valid_from"`
	ValidThrough openapi_types.Date        `json:"valid_through"`
}

// WeeklyScheduleSlotInput defines model for WeeklyScheduleSlotInput.
type WeeklyScheduleSlotInput struct {
	// EndTime Examples: 17:30
	EndTime LocalTime `json:"end_time"`

	// StartTime Examples: 17:30
	StartTime LocalTime `json:"start_time"`
	Weekday   int       `json:"weekday"`
}

// ClassId defines model for ClassId.
type ClassId = openapi_types.UUID

// HomeCursor defines model for HomeCursor.
type HomeCursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// RosterDate defines model for RosterDate.
type RosterDate = openapi_types.Date

// SessionId defines model for SessionId.
type SessionId = openapi_types.UUID

// StudentCursor defines model for StudentCursor.
type StudentCursor = string

// StudentId defines model for StudentId.
type StudentId = openapi_types.UUID

// StudentQuery defines model for StudentQuery.
type StudentQuery = string

// BadGateway The one error shape at the gateway boundary (spec 0001).
type BadGateway = Error

// BadRequest The one error shape at the gateway boundary (spec 0001).
type BadRequest = Error

// Conflict The one error shape at the gateway boundary (spec 0001).
type Conflict = Error

// Forbidden The one error shape at the gateway boundary (spec 0001).
type Forbidden = Error

// NotFound The one error shape at the gateway boundary (spec 0001).
type NotFound = Error

// RateLimited The one error shape at the gateway boundary (spec 0001).
type RateLimited = Error

// Unauthenticated The one error shape at the gateway boundary (spec 0001).
type Unauthenticated = Error

// CompleteGoogleSignInParams defines parameters for CompleteGoogleSignIn.
type CompleteGoogleSignInParams struct {
	// Code Google's authorization code. Absent when Google reports an error instead.
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State The single use state from the start call.
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Set by Google when the tutor cancelled or the exchange cannot proceed.
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// StartGoogleSignInParams defines parameters for StartGoogleSignIn.
type StartGoogleSignInParams struct {
	// Tz The browser's IANA timezone name, carried onto the tutor created by
	// the callback. Anything time.LoadLocation refuses falls back to
	// Asia/Ho_Chi_Minh.
	Tz *string `form:"tz,omitempty" json:"tz,omitempty"`

	// Lang The browser's language. Anything else falls back to vi.
	Lang *StartGoogleSignInParamsLang `form:"lang,omitempty" json:"lang,omitempty"`

	// RedirectTo Where in the app to land after signing in. Kept only when it is a
	// clean relative path and query with one leading slash, no fragment,
	// controls, backslash, scheme, or host.
	RedirectTo *string `form:"redirect_to,omitempty" json:"redirect_to,omitempty"`
}

// StartGoogleSignInParamsLang defines parameters for StartGoogleSignIn.
type StartGoogleSignInParamsLang string

// RefreshSessionParams defines parameters for RefreshSession.
type RefreshSessionParams struct {
	// Origin Supplied automatically by the browser and required by identity. It
	// must equal the configured app origin exactly.
	Origin *string `json:"Origin,omitempty"`
}

// SignOutParams defines parameters for SignOut.
type SignOutParams struct {
	// Origin Supplied automatically by the browser and required by identity. It
	// must equal the configured app origin exactly.
	Origin *string `json:"Origin,omitempty"`
}

// CreateClassParams defines parameters for CreateClass.
type CreateClassParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetClassRosterParams defines parameters for GetClassRoster.
type GetClassRosterParams struct {
	// Date Local roster date. Teaching defaults it from verified token timezone claims.
	Date *RosterDate `form:"date,omitempty" json:"date,omitempty"`
}

// ChangeClassRosterParams defines parameters for ChangeClassRoster.
type ChangeClassRosterParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// PutClassScheduleParams defines parameters for PutClassSchedule.
type PutClassScheduleParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// EndClassScheduleParams defines parameters for EndClassSchedule.
type EndClassScheduleParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetHomeParams defines parameters for GetHome.
type GetHomeParams struct {
	// Cursor Opaque cursor bound to the current tutor local date.
	Cursor *HomeCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetScheduleParams defines parameters for GetSchedule.
type GetScheduleParams struct {
	From            openapi_types.Date    `form:"from" json:"from"`
	Through         openapi_types.Date    `form:"through" json:"through"`
	ClassId         *[]openapi_types.UUID `form:"class_id,omitempty" json:"class_id,omitempty"`
	IncludeReplaced *bool                 `form:"include_replaced,omitempty" json:"include_replaced,omitempty"`
	HistoryLimit    *int                  `form:"history_limit,omitempty" json:"history_limit,omitempty"`
	HistoryCursor   *string               `form:"history_cursor,omitempty" json:"history_cursor,omitempty"`
}

// SaveSessionAttendanceParams defines parameters for SaveSessionAttendance.
type SaveSessionAttendanceParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CancelSessionParams defines parameters for CancelSession.
type CancelSessionParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// MoveSessionParams defines parameters for MoveSession.
type MoveSessionParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RestoreSessionParams defines parameters for RestoreSession.
type RestoreSessionParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListStudentsParams defines parameters for ListStudents.
type ListStudentsParams struct {
	// Q Case insensitive name or literal phone fragment, trimmed by teaching.
	Q *StudentQuery `form:"q,omitempty" json:"q,omitempty"`

	// Cursor Opaque cursor bound to the trimmed student search.
	Cursor *StudentCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateStudentParams defines parameters for CreateStudent.
type CreateStudentParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ArchiveStudentParams defines parameters for ArchiveStudent.
type ArchiveStudentParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateStudentParams defines parameters for UpdateStudent.
type UpdateStudentParams struct {
	// IdempotencyKey One browser generated UUID, retained until this create step succeeds.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateClassJSONRequestBody defines body for CreateClass for application/json ContentType.
type CreateClassJSONRequestBody = CreateClassRequest

// ChangeClassRosterJSONRequestBody defines body for ChangeClassRoster for application/json ContentType.
type ChangeClassRosterJSONRequestBody = ChangeRosterRequest

// PutClassScheduleJSONRequestBody defines body for PutClassSchedule for application/json ContentType.
type PutClassScheduleJSONRequestBody = PutScheduleRequest

// EndClassScheduleJSONRequestBody defines body for EndClassSchedule for application/json ContentType.
type EndClassScheduleJSONRequestBody = EndScheduleRequest

// SaveSessionAttendanceJSONRequestBody defines body for SaveSessionAttendance for application/json ContentType.
type SaveSessionAttendanceJSONRequestBody = SaveAttendanceRequest

// CancelSessionJSONRequestBody defines body for CancelSession for application/json ContentType.
type CancelSessionJSONRequestBody = SessionVersionRequest

// MoveSessionJSONRequestBody defines body for MoveSession for application/json ContentType.
type MoveSessionJSONRequestBody = MoveSessionRequest

// RestoreSessionJSONRequestBody defines body for RestoreSession for application/json ContentType.
type RestoreSessionJSONRequestBody = SessionVersionRequest

// CreateStudentJSONRequestBody defines body for CreateStudent for application/json ContentType.
type CreateStudentJSONRequestBody = CreateStudentRequest

// UpdateStudentJSONRequestBody defines body for UpdateStudent for application/json ContentType.
type UpdateStudentJSONRequestBody = UpdateStudentRequest
