// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TutorLanguage.
const (
	TutorLanguageEn TutorLanguage = "en"
	TutorLanguageVi TutorLanguage = "vi"
)

// Valid indicates whether the value is a known member of the TutorLanguage enum.
func (e TutorLanguage) Valid() bool {
	switch e {
	case TutorLanguageEn:
		return true
	case TutorLanguageVi:
		return true
	default:
		return false
	}
}

// Defines values for StartGoogleSignInParamsLang.
const (
	StartGoogleSignInParamsLangEn StartGoogleSignInParamsLang = "en"
	StartGoogleSignInParamsLangVi StartGoogleSignInParamsLang = "vi"
)

// Valid indicates whether the value is a known member of the StartGoogleSignInParamsLang enum.
func (e StartGoogleSignInParamsLang) Valid() bool {
	switch e {
	case StartGoogleSignInParamsLangEn:
		return true
	case StartGoogleSignInParamsLangVi:
		return true
	default:
		return false
	}
}

// Error The one error shape at the gateway boundary (spec 0001).
type Error struct {
	Error struct {
		// Code Examples: invalid_input
		Code      string `json:"code"`
		Message   string `json:"message"`
		RequestId string `json:"request_id"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

// ProjectionStatus notifications' own fact about how far its projection has caught up.
type ProjectionStatus struct {
	Recorded   bool               `json:"recorded"`
	RecordedAt *time.Time         `json:"recorded_at,omitempty"`
	TutorId    openapi_types.UUID `json:"tutor_id"`
	UpdatedAt  *time.Time         `json:"updated_at,omitempty"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Checks  *map[string]string `json:"checks,omitempty"`
	Service string             `json:"service"`
	Status  string             `json:"status"`
}

// Session What the browser holds after a refresh: an access token in memory only,
// and when it stops being valid. The refresh token itself is never in a
// body, only in the HttpOnly cookie beside it (spec 0004).
type Session struct {
	AccessExpiresAt time.Time `json:"access_expires_at"`
	AccessToken     string    `json:"access_token"`
}

// ThreadStatus defines model for ThreadStatus.
type ThreadStatus struct {
	// Projection notifications' own fact about how far its projection has caught up.
	Projection ProjectionStatus `json:"projection"`

	// ProjectionUnavailable Set when notifications did not answer. The tutor panel still
	// arrives, because one slow service degrades only its own panel.
	ProjectionUnavailable *string `json:"projection_unavailable,omitempty"`
	Tutor                 Tutor   `json:"tutor"`
}

// Tutor defines model for Tutor.
type Tutor struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Language    TutorLanguage       `json:"language"`
	Timezone    string              `json:"timezone"`
	TutorId     openapi_types.UUID  `json:"tutor_id"`
}

// TutorLanguage defines model for Tutor.Language.
type TutorLanguage string

// BadRequest The one error shape at the gateway boundary (spec 0001).
type BadRequest = Error

// Forbidden The one error shape at the gateway boundary (spec 0001).
type Forbidden = Error

// Unauthenticated The one error shape at the gateway boundary (spec 0001).
type Unauthenticated = Error

// CompleteGoogleSignInParams defines parameters for CompleteGoogleSignIn.
type CompleteGoogleSignInParams struct {
	// Code Google's authorization code. Absent when Google reports an error instead.
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State The single use state from the start call.
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Set by Google when the tutor cancelled or the exchange cannot proceed.
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// StartGoogleSignInParams defines parameters for StartGoogleSignIn.
type StartGoogleSignInParams struct {
	// Tz The browser's IANA timezone name, carried onto the tutor created by
	// the callback. Anything time.LoadLocation refuses falls back to
	// Asia/Ho_Chi_Minh.
	Tz *string `form:"tz,omitempty" json:"tz,omitempty"`

	// Lang The browser's language. Anything else falls back to vi.
	Lang *StartGoogleSignInParamsLang `form:"lang,omitempty" json:"lang,omitempty"`

	// RedirectTo Where in the app to land after signing in. Kept only when it is a
	// clean relative path and query with one leading slash, no fragment,
	// controls, backslash, scheme, or host.
	RedirectTo *string `form:"redirect_to,omitempty" json:"redirect_to,omitempty"`
}

// StartGoogleSignInParamsLang defines parameters for StartGoogleSignIn.
type StartGoogleSignInParamsLang string

// RefreshSessionParams defines parameters for RefreshSession.
type RefreshSessionParams struct {
	// Origin Supplied automatically by the browser and required by identity. It
	// must equal the configured app origin exactly.
	Origin *string `json:"Origin,omitempty"`
}

// SignOutParams defines parameters for SignOut.
type SignOutParams struct {
	// Origin Supplied automatically by the browser and required by identity. It
	// must equal the configured app origin exactly.
	Origin *string `json:"Origin,omitempty"`
}
