/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the gateway itself */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness of the gateway and every service behind it */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin Google sign in
         * @description Writes the in flight sign in (its state, PKCE verifier and nonce) and
         *     redirects the browser to Google. The browser follows this as a plain
         *     link, so it is a GET; nothing here needs a token, because this is what
         *     eventually produces one (spec 0004).
         */
        get: operations["startGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete Google sign in and start a session
         * @description Google sends the browser here. The code is exchanged and the ID token
         *     validated by identity, which holds the client secret; a first sign in
         *     creates the tutor and its identity.tutor.registered event in one
         *     transaction. The answer carries no access token on purpose: it sets the
         *     refresh cookie and lands the browser in the app, which then calls
         *     /api/auth/refresh, so a token never appears in a URL or in history.
         */
        get: operations["completeGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the refresh cookie for an access token
         * @description The one path to an access token, used both after the callback and on
         *     every boot, which is what makes a reload survive without a Google round
         *     trip. The cookie rotates on every call: presenting an already rotated
         *     token later than the grace window revokes the whole session family.
         *
         *     It is a POST rather than a GET because the method is half of the cross
         *     site protection, together with SameSite=Lax on the cookie.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Revokes every refresh token in this session family and clears the
         *     cookie. It answers 204 whether or not the cookie named a live session,
         *     because signing out twice is not an error.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed in tutor
         * @description The tutor comes from the sub claim of the verified token and from
         *     nothing else (INV-8).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The state of the skeleton's one end to end thread
         * @description A read the gateway fans out in parallel to two services (spec 0001,
         *     gateway read aggregation): the tutor from identity, which owns it, and
         *     from notifications whether its recipient projection has caught up yet.
         *     No identity fact is read from notifications' copy (INV-10).
         *
         *     The relay polls, so `projection.recorded` is false for the first moment
         *     after registering and true shortly after. That delay is the design
         *     working, not a fault.
         */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The one error shape at the gateway boundary (spec 0001). */
        Error: {
            error: {
                /** @example invalid_input */
                code: string;
                message: string;
                request_id: string;
            };
        };
        Health: {
            status: string;
            service: string;
        };
        Readiness: {
            status: string;
            service: string;
            checks?: {
                [key: string]: string;
            };
        };
        /**
         * @description What the browser holds after a refresh: an access token in memory only,
         *     and when it stops being valid. The refresh token itself is never in a
         *     body, only in the HttpOnly cookie beside it (spec 0004).
         */
        Session: {
            access_token: string;
            /** Format: date-time */
            access_expires_at: string;
        };
        Tutor: {
            /** Format: uuid */
            tutor_id: string;
            /** Format: email */
            email: string;
            display_name: string;
            timezone: string;
            /** @enum {string} */
            language: "vi" | "en";
            /** Format: date-time */
            created_at: string;
        };
        /** @description notifications' own fact about how far its projection has caught up. */
        ProjectionStatus: {
            /** Format: uuid */
            tutor_id: string;
            recorded: boolean;
            /** Format: date-time */
            recorded_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ThreadStatus: {
            tutor: components["schemas"]["Tutor"];
            projection: components["schemas"]["ProjectionStatus"];
            /**
             * @description Set when notifications did not answer. The tutor panel still
             *     arrives, because one slow service degrades only its own panel.
             */
            projection_unavailable?: string;
        };
    };
    responses: {
        /** @description The request was not acceptable */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid token was supplied */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gateway is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every service answered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one service did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    startGoogleSignIn: {
        parameters: {
            query?: {
                /**
                 * @description The browser's IANA timezone name, carried onto the tutor created by
                 *     the callback. Anything time.LoadLocation refuses falls back to
                 *     Asia/Ho_Chi_Minh.
                 */
                tz?: string;
                /** @description The browser's language. Anything else falls back to vi. */
                lang?: "vi" | "en";
                /**
                 * @description Where in the app to land after signing in. Kept only when it is a
                 *     path starting with a single slash, so it cannot become an open
                 *     redirect.
                 */
                redirect_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Google's authorize URL, or /signin?error=provider_error when the
             *     attempt could not be written.
             */
            302: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Google sign in is disabled in this local environment */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeGoogleSignIn: {
        parameters: {
            query?: {
                /** @description Google's authorization code. Absent when Google reports an error instead. */
                code?: string;
                /** @description The single use state from the start call. */
                state?: string;
                /** @description Set by Google when the tutor cancelled or the exchange cannot proceed. */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The app, or /signin?error=<code> with one of not_allowed,
             *     email_conflict, cancelled, expired_state or provider_error.
             */
            302: {
                headers: {
                    Location: string;
                    /** @description The rotating refresh token, HttpOnly and scoped to /api/auth. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Google sign in is disabled in this local environment */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A fresh access token, and a rotated cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is over */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed in tutor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tutor"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thread as it stands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadStatus"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
