/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the gateway itself */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness of the gateway and every service behind it */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin Google sign in
         * @description Writes the in flight sign in (its state, PKCE verifier, nonce, and the
         *     hash of an independent browser binding cookie) and redirects the browser
         *     to Google. The browser follows this as a plain link, so it is a GET;
         *     nothing here needs a token, because this is what eventually produces one
         *     (spec 0004).
         */
        get: operations["startGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete Google sign in and start a session
         * @description Google sends the browser here. The matching state and browser binding
         *     are required, then the code is exchanged and the ID token validated by
         *     identity, which holds the client secret. A first sign in creates the
         *     tutor and its identity.tutor.registered event in one transaction. The
         *     answer carries no access token on purpose: it sets the refresh cookie and
         *     lands the browser in the app, which then calls /api/auth/refresh, so a
         *     token never appears in a URL or in history.
         */
        get: operations["completeGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the refresh cookie for an access token
         * @description The one path to an access token, used both after the callback and on
         *     every boot, which is what makes a reload survive without a Google round
         *     trip. The cookie rotates on every call: presenting an already rotated
         *     token later than the grace window revokes the whole session family.
         *
         *     It is a POST and requires Origin to equal IDENTITY_APP_URL exactly.
         *     SameSite=Lax on the cookie is a supporting cross site protection.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Revokes the locked session family and clears the cookie. It answers 204
         *     whether or not the cookie named a live session, because signing out
         *     twice is not an error. Origin must equal IDENTITY_APP_URL exactly.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed in tutor
         * @description The tutor comes from the sub claim of the verified token and from
         *     nothing else (INV-8).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a class with its first session */
        post: operations["createClass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a student */
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{class_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a student to a class */
        post: operations["joinRoster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/attendance/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save or correct one attendance mark */
        put: operations["markAttendance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tutor and today's teaching work */
        get: operations["getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/billing-projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh only billing projection progress */
        get: operations["getHomeBillingProjection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The one error shape at the gateway boundary (spec 0001). */
        Error: {
            error: {
                /** @example invalid_input */
                code: string;
                message: string;
                request_id: string;
            };
        };
        Health: {
            status: string;
            service: string;
        };
        Readiness: {
            status: string;
            service: string;
            checks?: {
                [key: string]: string;
            };
        };
        /**
         * @description What the browser holds after a refresh: an access token in memory only,
         *     and when it stops being valid. The refresh token itself is never in a
         *     body, only in the HttpOnly cookie beside it (spec 0004).
         */
        Session: {
            access_token: string;
            /** Format: date-time */
            access_expires_at: string;
        };
        Tutor: {
            /** Format: uuid */
            tutor_id: string;
            /** Format: email */
            email: string;
            display_name: string;
            timezone: string;
            /** @enum {string} */
            language: "vi" | "en";
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        ClassColor: "red" | "rose" | "orange" | "green" | "blue" | "yellow" | "violet";
        /** @example 17:30 */
        LocalTime: string;
        FirstSessionInput: {
            /** Format: date */
            local_date: string;
            start_time: components["schemas"]["LocalTime"];
            end_time: components["schemas"]["LocalTime"];
        };
        CreateClassRequest: {
            name: string;
            color?: components["schemas"]["ClassColor"] | null;
            /** Format: int64 */
            rate_amount: number;
            first_session: components["schemas"]["FirstSessionInput"];
        };
        Class: {
            /** Format: uuid */
            class_id: string;
            name: string;
            color: components["schemas"]["ClassColor"];
            /** Format: int64 */
            rate_amount: number;
            /** @constant */
            currency: "VND";
            /** Format: date */
            rate_effective_from: string;
        };
        TeachingSession: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            class_id: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date */
            local_date: string;
        };
        CreateClassResponse: {
            class: components["schemas"]["Class"];
            first_session: components["schemas"]["TeachingSession"];
        };
        CreateStudentRequest: {
            name: string;
            phone?: string | null;
        };
        Student: {
            /** Format: uuid */
            student_id: string;
            name: string;
            phone: string | null;
        };
        JoinRosterRequest: {
            /** Format: uuid */
            student_id: string;
            /** Format: date */
            effective_from: string;
        };
        RosterPeriod: {
            /** Format: uuid */
            class_id: string;
            /** Format: uuid */
            student_id: string;
            /** Format: date */
            effective_from: string;
            /** Format: date */
            effective_to: string | null;
        };
        /** @enum {string} */
        AttendanceState: "Present" | "Absent";
        MarkAttendanceRequest: {
            state: components["schemas"]["AttendanceState"];
        };
        Attendance: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            student_id: string;
            state: components["schemas"]["AttendanceState"];
            /** Format: date-time */
            marked_at: string;
        };
        SetupDefaults: {
            /** Format: date */
            local_date: string;
            start_time: components["schemas"]["LocalTime"];
            end_time: components["schemas"]["LocalTime"];
        };
        HomeStudent: {
            /** Format: uuid */
            student_id: string;
            name: string;
            attendance_state: components["schemas"]["AttendanceState"] | null;
            /** Format: date-time */
            marked_at: string | null;
        };
        HomeSession: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            class_id: string;
            class_name: string;
            class_color: components["schemas"]["ClassColor"];
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date */
            local_date: string;
            students: components["schemas"]["HomeStudent"][];
        };
        TeachingHome: {
            request_time_zone: string;
            /** Format: date */
            local_date: string;
            /** Format: date-time */
            next_local_midnight_at: string;
            setup_defaults: components["schemas"]["SetupDefaults"];
            sessions: components["schemas"]["HomeSession"][];
            next_cursor: string | null;
        };
        BillingProjection: {
            /** @enum {string} */
            state: "waiting" | "active";
            /** Format: int64 */
            class_count: number;
            /** Format: int64 */
            session_count: number;
            /** Format: int64 */
            student_count: number;
            /** Format: int64 */
            open_roster_count: number;
            /** Format: int64 */
            attendance_count: number;
            /** Format: date-time */
            latest_updated_at: string | null;
        };
        HomeBillingProjection: {
            billing_projection: components["schemas"]["BillingProjection"] | null;
            billing_projection_unavailable: string | null;
        };
        Home: components["schemas"]["TeachingHome"] & {
            tutor: components["schemas"]["Tutor"];
            billing_projection: components["schemas"]["BillingProjection"] | null;
            billing_projection_unavailable: string | null;
        };
    };
    responses: {
        /** @description The request was not acceptable */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid token was supplied */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The browser origin may not change this session */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No owned resource matched */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested state conflicts with committed state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A required service did not answer successfully */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many authentication requests reached an applicable budget */
        RateLimited: {
            headers: {
                /** @description Whole seconds until every applicable rate budget can admit one request. */
                "Retry-After": number;
                /** @description Prevents a refusal from being stored by browsers or intermediaries. */
                "Cache-Control": "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description One browser generated UUID, retained until this create step succeeds. */
        IdempotencyKey: string;
        ClassId: string;
        SessionId: string;
        StudentId: string;
        /** @description Opaque cursor bound to the current tutor local date. */
        HomeCursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gateway is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every service answered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one service did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    startGoogleSignIn: {
        parameters: {
            query?: {
                /**
                 * @description The browser's IANA timezone name, carried onto the tutor created by
                 *     the callback. Anything time.LoadLocation refuses falls back to
                 *     Asia/Ho_Chi_Minh.
                 */
                tz?: string;
                /** @description The browser's language. Anything else falls back to vi. */
                lang?: "vi" | "en";
                /**
                 * @description Where in the app to land after signing in. Kept only when it is a
                 *     clean relative path and query with one leading slash, no fragment,
                 *     controls, backslash, scheme, or host.
                 */
                redirect_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Google's authorize URL, or /signin?error=provider_error when the
             *     attempt could not be written. A rate limited request instead uses
             *     /signin?error=rate_limited and carries Retry-After plus no-store.
             */
            302: {
                headers: {
                    Location: string;
                    /** @description Whole seconds until every applicable rate budget can admit one request. */
                    "Retry-After"?: number;
                    /** @description Present as no-store on a rate limited redirect. */
                    "Cache-Control"?: "no-store";
                    /** @description The short lived HttpOnly browser binding cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Google sign in is disabled in this local environment */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeGoogleSignIn: {
        parameters: {
            query?: {
                /** @description Google's authorization code. Absent when Google reports an error instead. */
                code?: string;
                /** @description The single use state from the start call. */
                state?: string;
                /** @description Set by Google when the tutor cancelled or the exchange cannot proceed. */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The app, or /signin?error=<code> with one of not_allowed,
             *     email_conflict, cancelled, expired_state, provider_error or
             *     rate_limited. A rate limited redirect carries Retry-After plus
             *     no-store.
             */
            302: {
                headers: {
                    Location: string;
                    /** @description Whole seconds until every applicable rate budget can admit one request. */
                    "Retry-After"?: number;
                    /** @description Present as no-store on a rate limited redirect. */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description The browser binding clear, plus the rotating refresh token on
                     *     success. Both are HttpOnly and repeat their original paths.
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Google sign in is disabled in this local environment */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Supplied automatically by the browser and required by identity. It
                 *     must equal the configured app origin exactly.
                 */
                Origin?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A fresh access token, and a rotated cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /**
             * @description The refresh cookie is missing, unknown, expired, revoked, or reused
             *     outside the grace window. The response clears that cookie.
             */
            401: {
                headers: {
                    /** @description Clears the refresh cookie with the same path and flags. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Supplied automatically by the browser and required by identity. It
                 *     must equal the configured app origin exactly.
                 */
                Origin?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is over and the refresh cookie is cleared */
            204: {
                headers: {
                    /** @description Clears the refresh cookie with the same path and flags. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed in tutor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tutor"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createClass: {
        parameters: {
            query?: never;
            header: {
                /** @description One browser generated UUID, retained until this create step succeeds. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassRequest"];
            };
        };
        responses: {
            /** @description The original class and first session for a safe retry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateClassResponse"];
                };
            };
            /** @description The class and first session were created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateClassResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header: {
                /** @description One browser generated UUID, retained until this create step succeeds. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentRequest"];
            };
        };
        responses: {
            /** @description The original student for a safe retry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            /** @description The student was registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
        };
    };
    joinRoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: components["parameters"]["ClassId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRosterRequest"];
            };
        };
        responses: {
            /** @description The exact open roster period already existed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPeriod"];
                };
            };
            /** @description The roster period was opened */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPeriod"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    markAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
                student_id: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkAttendanceRequest"];
            };
        };
        responses: {
            /** @description The canonical attendance row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attendance"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getHome: {
        parameters: {
            query?: {
                /** @description Opaque cursor bound to the current tutor local date. */
                cursor?: components["parameters"]["HomeCursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required identity and teaching facts plus optional billing progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            502: components["responses"]["BadGateway"];
        };
    };
    getHomeBillingProjection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Billing progress or its isolated unavailable state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeBillingProjection"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
