global:
  images:
    envoyGateway:
      image: docker.io/envoyproxy/gateway@sha256:6f40c7b218b4ff1c4cb481923ed2c9a7634580365913434dd5dda9e954c0114b
      pullPolicy: IfNotPresent
    envoyProxy:
      image: docker.io/envoyproxy/envoy@sha256:7877ad87afd7459e1bd2a077ff601fec7c93aeecd62e71664560d96328c62cf4
      pullPolicy: IfNotPresent
deployment:
  replicas: 1
  envoyGateway:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    logging:
      level:
        default: info
