// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloseRosterPeriod(ctx context.Context, arg CloseRosterPeriodParams) error
	// CurrentBillingRunGeneration only tells the handler which number to attempt. It
	// needs no lock and no SELECT ... FOR UPDATE: the unique constraint on
	// (tutor_id, period_year, period_month, generation) is what actually decides a
	// race, and the loser reads the winner's invoices. An absent row means no run
	// yet, so the next generation is 1.
	CurrentBillingRunGeneration(ctx context.Context, arg CurrentBillingRunGenerationParams) (CurrentBillingRunGenerationRow, error)
	GetBillingRun(ctx context.Context, arg GetBillingRunParams) (BillingRun, error)
	GetInvoice(ctx context.Context, arg GetInvoiceParams) (Invoice, error)
	GetInvoiceNumberCounter(ctx context.Context, arg GetInvoiceNumberCounterParams) (InvoiceNumberCounter, error)
	// GetInvoiceProfile returns is_complete beside the fields, so the month end
	// refusal and the profile screen read the one gate rather than each testing its
	// own field list (AC-12).
	// The column order is the table's own, so sqlc hands back the one
	// invoice_profiles row type rather than a second shape of the same row.
	GetInvoiceProfile(ctx context.Context, tutorID uuid.UUID) (InvoiceProfile, error)
	InsertBillingRun(ctx context.Context, arg InsertBillingRunParams) (BillingRun, error)
	// InsertInvoice freezes the render block at issue: the student name and the five
	// payee fields are copied in, so a re render years later prints the file the
	// tutor already sent and a later bank account change cannot reach backwards into
	// it (INV-9).
	InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (Invoice, error)
	// InsertInvoiceLine keeps both the frozen values and the session_id they came
	// from. The id is for tracing during a dispute and is never joined at render
	// time.
	InsertInvoiceLine(ctx context.Context, arg InsertInvoiceLineParams) (InvoiceLine, error)
	// ListBillableSessions is the month end run's one read of the projections. The
	// period is a range over local_date, because there is no stored month column a
	// session.moved could leave stale (AC-9). Only state = 'Present' bills: a
	// missing attendance row is unmarked, which for money is the same answer as
	// 'Absent'. Membership uses the one coverage predicate spec 0003 states for all
	// three services, inclusive at both ends, so this and notifications'
	// ListDigestSessions can never disagree about who was in a class on a day.
	//
	// The rate joins LATERAL and LEFT, and rate_known says whether it was there: a
	// session whose class has no rate row on or before its date comes back with
	// rate_known false rather than vanishing, so the run refuses with rate_missing
	// instead of silently billing less. It is a flag rather than a null rate because
	// a rate of zero is legal (a genuinely free lesson), so zero and missing have to
	// be two different answers. The rate itself comes back coalesced, so the type
	// stays plain int64 dong and rate_known is the only place the question "was there
	// a rate at all" is answered.
	ListBillableSessions(ctx context.Context, arg ListBillableSessionsParams) ([]ListBillableSessionsRow, error)
	ListInvoiceLines(ctx context.Context, arg ListInvoiceLinesParams) ([]InvoiceLine, error)
	ListInvoicesForPeriod(ctx context.Context, arg ListInvoicesForPeriodParams) ([]ListInvoicesForPeriodRow, error)
	MarkSessionCancelled(ctx context.Context, arg MarkSessionCancelledParams) error
	// MarkStudentRemoved stamps the end from the envelope occurred_at, because
	// teaching.student.removed carries no timestamp of its own (INV-4). The first end
	// wins, so a replay leaves the value it already recorded.
	MarkStudentRemoved(ctx context.Context, arg MarkStudentRemovedParams) error
	OpenRosterPeriod(ctx context.Context, arg OpenRosterPeriodParams) error
	// RateInForceOn is the newest row on or before the date, which the primary key
	// already orders: a backwards scan of one index, no extra descending index. An
	// absent row is what the run turns into rate_missing.
	RateInForceOn(ctx context.Context, arg RateInForceOnParams) (RateInForceOnRow, error)
	// SaveInvoiceProfile is the tutor's own write, from the profile screen. Every
	// field here is theirs; no event carries any of it, so bank details never reach
	// the broker.
	SaveInvoiceProfile(ctx context.Context, arg SaveInvoiceProfileParams) (InvoiceProfile, error)
	// ------------------------------------------------------- authoritative records
	// No replay may rewrite anything below this line (AC-8).
	// SeedInvoiceProfile is the one statement a consumer runs on an authoritative
	// table, and it writes no field: identity.tutor.registered only causes the empty
	// row to exist. That is what lets a replay recreate a missing row without ever
	// overwriting bank details the tutor typed.
	SeedInvoiceProfile(ctx context.Context, tutorID uuid.UUID) error
	// TakeNextInvoiceNumber bumps the counter inside the run's transaction and
	// returns the number it just took. A row of its own rather than a max over live
	// invoices, because a voided invoice keeps its number spent. Two concurrent
	// takes serialise on the row and can never return the same sequence.
	TakeNextInvoiceNumber(ctx context.Context, arg TakeNextInvoiceNumberParams) (int32, error)
	UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) error
	UpsertClass(ctx context.Context, arg UpsertClassParams) error
	// UpsertClassRate appends the dated history billing owns. teaching.class.created
	// seeds the first row from its rate_effective_from and
	// teaching.class.rate.changed appends from its effective_from: two event fields
	// writing one column. A corrected rate for the same date is an upsert, never a
	// second row, because two rows for one class on one date would make "the rate in
	// force" ambiguous.
	UpsertClassRate(ctx context.Context, arg UpsertClassRateParams) error
	// UpsertSession serves teaching.session.scheduled and teaching.session.moved
	// alike: a move is the same three columns at new values.
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
	// Hand written SQL for billing, compiled to typed Go by sqlc (STK-3). No ORM,
	// and no SQL assembled by string concatenation at runtime.
	//
	// Every statement here names tutor_id (INV-8, AC-4), which comes from the sub
	// claim of the verified token and never from an input. The file keeps the two
	// halves of 00002_billing_model.sql in the same order, with the same line
	// between them: the projection statements above it are run only by
	// internal/consumer, the authoritative ones below it only by internal/handler.
	// ---------------------------------------------------------------- projections
	// Every one of these is an upsert on the identifying key the event already
	// carries, so a redelivery and a full replay both land on the same row and
	// change nothing the second time (AC-7, INV-5, INV-11).
	UpsertStudent(ctx context.Context, arg UpsertStudentParams) error
}

var _ Querier = (*Queries)(nil)
