image:
  repository: rancher/mirrored-library-traefik
  tag: "3.7.8"
  digest: sha256:4299bbed850421258fc5448c2e0e6ad350981d4d335a68de11b92448aedbefe5
  pullPolicy: IfNotPresent
versionOverride: "v3.7.8"
deployment:
  replicas: 1
  revisionHistoryLimit: 2
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik
providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    publishedService:
      enabled: true
  kubernetesGateway:
    enabled: false
logs:
  general:
    level: INFO
    format: json
  access:
    enabled: true
    format: json
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
podSecurityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
