// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	SessionID uuid.UUID
	TutorID   uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}

type ConsumerFailure struct {
	ConsumerName      string
	SourceTopic       string
	SourcePartition   int32
	SourceOffset      int64
	EventID           pgtype.UUID
	TutorID           pgtype.UUID
	FailureCategory   string
	FailedAt          time.Time
	ResolvedAt        pgtype.Timestamptz
	Resolution        pgtype.Text
	ResolutionCode    pgtype.Text
	ResolvedBy        pgtype.Text
	RepairReference   pgtype.Text
	ResolutionHistory []byte
}

type ConsumerReadiness struct {
	ConsumerName         string
	ProjectionGeneration uuid.UUID
	State                string
	UpdatedAt            time.Time
}

type ConsumerReplayManifest struct {
	ConsumerName         string
	ProjectionGeneration uuid.UUID
	SourceTopic          string
	TopicIdentity        string
	PartitionSet         []byte
	EarliestOffsets      []byte
	CapturedEndOffsets   []byte
	CompletedOffsets     []byte
	StartedAt            time.Time
	CompletedAt          pgtype.Timestamptz
	OperatorIdentity     string
}

type HandledEvent struct {
	ConsumerName string
	EventID      uuid.UUID
	HandledAt    time.Time
}

type LoginAttempt struct {
	State              string
	CodeVerifier       string
	Nonce              string
	BrowserBindingHash []byte
	RedirectTo         string
	Timezone           string
	Language           string
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

type Outbox struct {
	ID           int64
	EventID      uuid.UUID
	EventName    string
	EventVersion int32
	OccurredAt   time.Time
	TutorID      uuid.UUID
	KeyKind      string
	KeyValue     uuid.UUID
	RequestID    string
	Topic        string
	Envelope     []byte
	CreatedAt    time.Time
	PublishedAt  pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash []byte
	SessionID uuid.UUID
	IssuedAt  time.Time
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
}

type Tutor struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TutorIdentity struct {
	TutorID         uuid.UUID
	Provider        string
	ProviderSubject string
	ProviderEmail   string
	LinkedAt        time.Time
}
