// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type HandledEvent struct {
	ConsumerName string
	EventID      uuid.UUID
	HandledAt    time.Time
}

type LoginAttempt struct {
	State        string
	CodeVerifier string
	Nonce        string
	RedirectTo   string
	Timezone     string
	Language     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type Outbox struct {
	ID           int64
	EventID      uuid.UUID
	EventName    string
	EventVersion int32
	OccurredAt   time.Time
	TutorID      uuid.UUID
	KeyKind      string
	KeyValue     uuid.UUID
	RequestID    string
	Topic        string
	Envelope     []byte
	CreatedAt    time.Time
	PublishedAt  pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash []byte
	SessionID uuid.UUID
	TutorID   uuid.UUID
	IssuedAt  time.Time
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Tutor struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TutorIdentity struct {
	TutorID         uuid.UUID
	Provider        string
	ProviderSubject string
	ProviderEmail   string
	LinkedAt        time.Time
}
