// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Single use is the delete itself, inside the callback transaction, so a
	// replayed callback finds nothing. An expired attempt is left for the sweep
	// rather than consumed, which is what makes AC-8 one answer for both cases.
	ConsumeLoginAttempt(ctx context.Context, state string) (ConsumeLoginAttemptRow, error)
	DeleteExpiredLoginAttempts(ctx context.Context) (int64, error)
	// The sweep. A revoked row is kept for a while on purpose: presenting it again
	// is how a stolen copy shows up, and a deleted row is indistinguishable from
	// one that never existed.
	DeleteFinishedAuthSessions(ctx context.Context, revokedAt pgtype.Timestamptz) (int64, error)
	ExtendAuthSession(ctx context.Context, arg ExtendAuthSessionParams) error
	// The callback reads the attempt before it talks to Google, because the PKCE
	// verifier it holds is what the exchange needs. Claiming it is a separate
	// statement, run inside the transaction that writes the tutor.
	GetLoginAttempt(ctx context.Context, state string) (GetLoginAttemptRow, error)
	// This lookup takes no lock. session_id is immutable, and it only tells the
	// caller which auth_sessions row must be locked before it may inspect the token.
	GetRefreshTokenSessionID(ctx context.Context, tokenHash []byte) (uuid.UUID, error)
	GetTutor(ctx context.Context, tutorID uuid.UUID) (GetTutorRow, error)
	GetTutorByEmail(ctx context.Context, email string) (GetTutorByEmailRow, error)
	GetTutorByProviderSubject(ctx context.Context, arg GetTutorByProviderSubjectParams) (GetTutorByProviderSubjectRow, error)
	InsertAuthSession(ctx context.Context, arg InsertAuthSessionParams) (AuthSession, error)
	// The sign in attempt and the locked refresh token family behind a session
	// (spec 0004). Every value is parameterized, and every family transition locks
	// auth_sessions before it locks the presented token.
	InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	// Hand written SQL, compiled to typed Go by sqlc (STK-3). No ORM, and no SQL
	// assembled by string concatenation at runtime.
	InsertTutor(ctx context.Context, arg InsertTutorParams) (InsertTutorRow, error)
	// The link to an external account. provider_subject is the identity; the email
	// beside it is only a copy of what Google last said.
	InsertTutorIdentity(ctx context.Context, arg InsertTutorIdentityParams) (TutorIdentity, error)
	LockAuthSession(ctx context.Context, sessionID uuid.UUID) (AuthSession, error)
	LockRefreshToken(ctx context.Context, arg LockRefreshTokenParams) (RefreshToken, error)
	MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	// The email copy is kept in step with Google's, which owns it. updated_at is
	// what identity.tutor.profile.changed stamps; the event itself carries only
	// spec 0001's five fields.
	UpdateTutorFromProvider(ctx context.Context, arg UpdateTutorFromProviderParams) (UpdateTutorFromProviderRow, error)
	UpdateTutorIdentityEmail(ctx context.Context, arg UpdateTutorIdentityEmailParams) error
}

var _ Querier = (*Queries)(nil)
