// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Single use is the delete itself, inside the callback transaction, so a
	// replayed callback finds nothing. An expired attempt is left for the sweep
	// rather than consumed, which is what makes AC-8 one answer for both cases.
	ConsumeLoginAttempt(ctx context.Context, state string) (ConsumeLoginAttemptRow, error)
	DeleteExpiredLoginAttempts(ctx context.Context) (int64, error)
	// The sweep. A revoked row is kept for a while on purpose: presenting it again
	// is how a stolen copy shows up, and a deleted row is indistinguishable from
	// one that never existed.
	DeleteFinishedRefreshTokens(ctx context.Context, revokedAt pgtype.Timestamptz) (int64, error)
	// The callback reads the attempt before it talks to Google, because the PKCE
	// verifier it holds is what the exchange needs. Claiming it is a separate
	// statement, run inside the transaction that writes the tutor.
	GetLoginAttempt(ctx context.Context, state string) (GetLoginAttemptRow, error)
	GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetTutor(ctx context.Context, tutorID uuid.UUID) (GetTutorRow, error)
	GetTutorByEmail(ctx context.Context, email string) (GetTutorByEmailRow, error)
	GetTutorByProviderSubject(ctx context.Context, arg GetTutorByProviderSubjectParams) (GetTutorByProviderSubjectRow, error)
	// The sign in attempt and the refresh token family behind a session (spec
	// 0004). These are the two tables that cannot filter by tutor_id: an attempt
	// exists before the tutor does, and a refresh token is presented before any
	// token names a tutor. Both are identified instead by an unguessable value from
	// crypto/rand, which is what test/model's tenancy guard insists each one names.
	InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	// Hand written SQL, compiled to typed Go by sqlc (STK-3). No ORM, and no SQL
	// assembled by string concatenation at runtime.
	InsertTutor(ctx context.Context, arg InsertTutorParams) (InsertTutorRow, error)
	// The link to an external account. provider_subject is the identity; the email
	// beside it is only a copy of what Google last said.
	InsertTutorIdentity(ctx context.Context, arg InsertTutorIdentityParams) (TutorIdentity, error)
	// The first use of a token is a single statement, so two tabs racing cannot
	// both win it: the loser reads used_at back and falls into the grace window
	// branch instead of being treated as theft.
	MarkRefreshTokenUsed(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) (int64, error)
	// The email copy is kept in step with Google's, which owns it. updated_at is
	// what identity.tutor.profile.changed stamps; the event itself carries only
	// spec 0001's five fields.
	UpdateTutorFromProvider(ctx context.Context, arg UpdateTutorFromProviderParams) (UpdateTutorFromProviderRow, error)
	UpdateTutorIdentityEmail(ctx context.Context, arg UpdateTutorIdentityEmailParams) error
}

var _ Querier = (*Queries)(nil)
