// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeLoginAttempt = `-- name: ConsumeLoginAttempt :one
DELETE FROM login_attempts
WHERE state = $1 AND expires_at > now()
RETURNING state, code_verifier, nonce, browser_binding_hash,
          redirect_to, timezone, language
`

type ConsumeLoginAttemptRow struct {
	State              string
	CodeVerifier       string
	Nonce              string
	BrowserBindingHash []byte
	RedirectTo         string
	Timezone           string
	Language           string
}

// Single use is the delete itself, inside the callback transaction, so a
// replayed callback finds nothing. An expired attempt is left for the sweep
// rather than consumed, which is what makes AC-8 one answer for both cases.
func (q *Queries) ConsumeLoginAttempt(ctx context.Context, state string) (ConsumeLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, consumeLoginAttempt, state)
	var i ConsumeLoginAttemptRow
	err := row.Scan(
		&i.State,
		&i.CodeVerifier,
		&i.Nonce,
		&i.BrowserBindingHash,
		&i.RedirectTo,
		&i.Timezone,
		&i.Language,
	)
	return i, err
}

const deleteExpiredLoginAttempts = `-- name: DeleteExpiredLoginAttempts :execrows
DELETE FROM login_attempts
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredLoginAttempts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFinishedAuthSessions = `-- name: DeleteFinishedAuthSessions :execrows
DELETE FROM auth_sessions
WHERE expires_at <= transaction_timestamp()
   OR (revoked_at IS NOT NULL AND revoked_at <= $1)
`

// The sweep. A revoked row is kept for a while on purpose: presenting it again
// is how a stolen copy shows up, and a deleted row is indistinguishable from
// one that never existed.
func (q *Queries) DeleteFinishedAuthSessions(ctx context.Context, revokedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedAuthSessions, revokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendAuthSession = `-- name: ExtendAuthSession :exec
UPDATE auth_sessions
SET expires_at = $2
WHERE session_id = $1 AND revoked_at IS NULL
`

type ExtendAuthSessionParams struct {
	SessionID uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) ExtendAuthSession(ctx context.Context, arg ExtendAuthSessionParams) error {
	_, err := q.db.Exec(ctx, extendAuthSession, arg.SessionID, arg.ExpiresAt)
	return err
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT state, code_verifier, nonce, browser_binding_hash,
       redirect_to, timezone, language
FROM login_attempts
WHERE state = $1 AND expires_at > now()
`

type GetLoginAttemptRow struct {
	State              string
	CodeVerifier       string
	Nonce              string
	BrowserBindingHash []byte
	RedirectTo         string
	Timezone           string
	Language           string
}

// The callback reads the attempt before it talks to Google, because the PKCE
// verifier it holds is what the exchange needs. Claiming it is a separate
// statement, run inside the transaction that writes the tutor.
func (q *Queries) GetLoginAttempt(ctx context.Context, state string) (GetLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, state)
	var i GetLoginAttemptRow
	err := row.Scan(
		&i.State,
		&i.CodeVerifier,
		&i.Nonce,
		&i.BrowserBindingHash,
		&i.RedirectTo,
		&i.Timezone,
		&i.Language,
	)
	return i, err
}

const getRefreshTokenSessionID = `-- name: GetRefreshTokenSessionID :one
SELECT session_id
FROM refresh_tokens
WHERE token_hash = $1
`

// This lookup takes no lock. session_id is immutable, and it only tells the
// caller which auth_sessions row must be locked before it may inspect the token.
func (q *Queries) GetRefreshTokenSessionID(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenSessionID, tokenHash)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const insertAuthSession = `-- name: InsertAuthSession :one
INSERT INTO auth_sessions (session_id, tutor_id, expires_at)
VALUES ($1, $2, $3)
RETURNING session_id, tutor_id, created_at, expires_at, revoked_at
`

type InsertAuthSessionParams struct {
	SessionID uuid.UUID
	TutorID   uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertAuthSession(ctx context.Context, arg InsertAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, insertAuthSession, arg.SessionID, arg.TutorID, arg.ExpiresAt)
	var i AuthSession
	err := row.Scan(
		&i.SessionID,
		&i.TutorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec

INSERT INTO login_attempts (
    state, code_verifier, nonce, browser_binding_hash,
    redirect_to, timezone, language, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLoginAttemptParams struct {
	State              string
	CodeVerifier       string
	Nonce              string
	BrowserBindingHash []byte
	RedirectTo         string
	Timezone           string
	Language           string
	ExpiresAt          time.Time
}

// The sign in attempt and the locked refresh token family behind a session
// (spec 0004). Every value is parameterized, and every family transition locks
// auth_sessions before it locks the presented token.
func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt,
		arg.State,
		arg.CodeVerifier,
		arg.Nonce,
		arg.BrowserBindingHash,
		arg.RedirectTo,
		arg.Timezone,
		arg.Language,
		arg.ExpiresAt,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (token_hash, session_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, session_id, issued_at, expires_at, used_at
`

type InsertRefreshTokenParams struct {
	TokenHash []byte
	SessionID uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.TokenHash, arg.SessionID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const lockAuthSession = `-- name: LockAuthSession :one
SELECT session_id, tutor_id, created_at, expires_at, revoked_at
FROM auth_sessions s
WHERE s.session_id = $1
FOR UPDATE
`

func (q *Queries) LockAuthSession(ctx context.Context, sessionID uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, lockAuthSession, sessionID)
	var i AuthSession
	err := row.Scan(
		&i.SessionID,
		&i.TutorID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockRefreshToken = `-- name: LockRefreshToken :one
SELECT token_hash, session_id, issued_at, expires_at, used_at
FROM refresh_tokens
WHERE token_hash = $1 AND session_id = $2
FOR UPDATE
`

type LockRefreshTokenParams struct {
	TokenHash []byte
	SessionID uuid.UUID
}

func (q *Queries) LockRefreshToken(ctx context.Context, arg LockRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, lockRefreshToken, arg.TokenHash, arg.SessionID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens
SET used_at = $3
WHERE token_hash = $1 AND session_id = $2 AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	TokenHash []byte
	SessionID uuid.UUID
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.TokenHash, arg.SessionID, arg.UsedAt)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_sessions
SET revoked_at = $2
WHERE session_id = $1 AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	SessionID uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.SessionID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
