// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeLoginAttempt = `-- name: ConsumeLoginAttempt :one
DELETE FROM login_attempts
WHERE state = $1 AND expires_at > now()
RETURNING state, code_verifier, nonce, redirect_to, timezone, language
`

type ConsumeLoginAttemptRow struct {
	State        string
	CodeVerifier string
	Nonce        string
	RedirectTo   string
	Timezone     string
	Language     string
}

// Single use is the delete itself, inside the callback transaction, so a
// replayed callback finds nothing. An expired attempt is left for the sweep
// rather than consumed, which is what makes AC-8 one answer for both cases.
func (q *Queries) ConsumeLoginAttempt(ctx context.Context, state string) (ConsumeLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, consumeLoginAttempt, state)
	var i ConsumeLoginAttemptRow
	err := row.Scan(
		&i.State,
		&i.CodeVerifier,
		&i.Nonce,
		&i.RedirectTo,
		&i.Timezone,
		&i.Language,
	)
	return i, err
}

const deleteExpiredLoginAttempts = `-- name: DeleteExpiredLoginAttempts :execrows
DELETE FROM login_attempts
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredLoginAttempts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFinishedRefreshTokens = `-- name: DeleteFinishedRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at <= now() OR (revoked_at IS NOT NULL AND revoked_at <= $1)
`

// The sweep. A revoked row is kept for a while on purpose: presenting it again
// is how a stolen copy shows up, and a deleted row is indistinguishable from
// one that never existed.
func (q *Queries) DeleteFinishedRefreshTokens(ctx context.Context, revokedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedRefreshTokens, revokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT state, code_verifier, nonce, redirect_to, timezone, language
FROM login_attempts
WHERE state = $1 AND expires_at > now()
`

type GetLoginAttemptRow struct {
	State        string
	CodeVerifier string
	Nonce        string
	RedirectTo   string
	Timezone     string
	Language     string
}

// The callback reads the attempt before it talks to Google, because the PKCE
// verifier it holds is what the exchange needs. Claiming it is a separate
// statement, run inside the transaction that writes the tutor.
func (q *Queries) GetLoginAttempt(ctx context.Context, state string) (GetLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, state)
	var i GetLoginAttemptRow
	err := row.Scan(
		&i.State,
		&i.CodeVerifier,
		&i.Nonce,
		&i.RedirectTo,
		&i.Timezone,
		&i.Language,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token_hash, session_id, tutor_id, issued_at, expires_at, used_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.TutorID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec

INSERT INTO login_attempts (state, code_verifier, nonce, redirect_to, timezone, language, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLoginAttemptParams struct {
	State        string
	CodeVerifier string
	Nonce        string
	RedirectTo   string
	Timezone     string
	Language     string
	ExpiresAt    time.Time
}

// The sign in attempt and the refresh token family behind a session (spec
// 0004). These are the two tables that cannot filter by tutor_id: an attempt
// exists before the tutor does, and a refresh token is presented before any
// token names a tutor. Both are identified instead by an unguessable value from
// crypto/rand, which is what test/model's tenancy guard insists each one names.
func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt,
		arg.State,
		arg.CodeVerifier,
		arg.Nonce,
		arg.RedirectTo,
		arg.Timezone,
		arg.Language,
		arg.ExpiresAt,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (token_hash, session_id, tutor_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token_hash, session_id, tutor_id, issued_at, expires_at, used_at, revoked_at
`

type InsertRefreshTokenParams struct {
	TokenHash []byte
	SessionID uuid.UUID
	TutorID   uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.TokenHash,
		arg.SessionID,
		arg.TutorID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.TutorID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :one
UPDATE refresh_tokens
SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now()
RETURNING token_hash, session_id, tutor_id, issued_at, expires_at, used_at, revoked_at
`

// The first use of a token is a single statement, so two tabs racing cannot
// both win it: the loser reads used_at back and falls into the grace window
// branch instead of being treated as theft.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, markRefreshTokenUsed, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.TutorID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE tutor_id = $1 AND session_id = $2 AND revoked_at IS NULL
`

type RevokeSessionFamilyParams struct {
	TutorID   uuid.UUID
	SessionID uuid.UUID
}

func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionFamily, arg.TutorID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
