// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tutors.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTutor = `-- name: GetTutor :one
SELECT tutor_id, email, display_name, timezone, language, created_at
FROM tutors
WHERE tutor_id = $1
`

type GetTutorRow struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	CreatedAt   time.Time
}

func (q *Queries) GetTutor(ctx context.Context, tutorID uuid.UUID) (GetTutorRow, error) {
	row := q.db.QueryRow(ctx, getTutor, tutorID)
	var i GetTutorRow
	err := row.Scan(
		&i.TutorID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const getTutorByEmail = `-- name: GetTutorByEmail :one
SELECT tutor_id, email, display_name, timezone, language, created_at
FROM tutors
WHERE email = $1
`

type GetTutorByEmailRow struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	CreatedAt   time.Time
}

func (q *Queries) GetTutorByEmail(ctx context.Context, email string) (GetTutorByEmailRow, error) {
	row := q.db.QueryRow(ctx, getTutorByEmail, email)
	var i GetTutorByEmailRow
	err := row.Scan(
		&i.TutorID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const getTutorByProviderSubject = `-- name: GetTutorByProviderSubject :one
SELECT t.tutor_id, t.email, t.display_name, t.timezone, t.language, t.created_at,
       i.provider_email
FROM tutor_identities i
JOIN tutors t ON t.tutor_id = i.tutor_id
WHERE i.provider = $1 AND i.provider_subject = $2
`

type GetTutorByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

type GetTutorByProviderSubjectRow struct {
	TutorID       uuid.UUID
	Email         string
	DisplayName   string
	Timezone      string
	Language      string
	CreatedAt     time.Time
	ProviderEmail string
}

func (q *Queries) GetTutorByProviderSubject(ctx context.Context, arg GetTutorByProviderSubjectParams) (GetTutorByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, getTutorByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i GetTutorByProviderSubjectRow
	err := row.Scan(
		&i.TutorID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.Language,
		&i.CreatedAt,
		&i.ProviderEmail,
	)
	return i, err
}

const insertTutor = `-- name: InsertTutor :one

INSERT INTO tutors (tutor_id, email, display_name, timezone, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING tutor_id, email, display_name, timezone, language, created_at
`

type InsertTutorParams struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
}

type InsertTutorRow struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	CreatedAt   time.Time
}

// Hand written SQL, compiled to typed Go by sqlc (STK-3). No ORM, and no SQL
// assembled by string concatenation at runtime.
func (q *Queries) InsertTutor(ctx context.Context, arg InsertTutorParams) (InsertTutorRow, error) {
	row := q.db.QueryRow(ctx, insertTutor,
		arg.TutorID,
		arg.Email,
		arg.DisplayName,
		arg.Timezone,
		arg.Language,
	)
	var i InsertTutorRow
	err := row.Scan(
		&i.TutorID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const insertTutorIdentity = `-- name: InsertTutorIdentity :one
INSERT INTO tutor_identities (tutor_id, provider, provider_subject, provider_email)
VALUES ($1, $2, $3, $4)
RETURNING tutor_id, provider, provider_subject, provider_email, linked_at
`

type InsertTutorIdentityParams struct {
	TutorID         uuid.UUID
	Provider        string
	ProviderSubject string
	ProviderEmail   string
}

// The link to an external account. provider_subject is the identity; the email
// beside it is only a copy of what Google last said.
func (q *Queries) InsertTutorIdentity(ctx context.Context, arg InsertTutorIdentityParams) (TutorIdentity, error) {
	row := q.db.QueryRow(ctx, insertTutorIdentity,
		arg.TutorID,
		arg.Provider,
		arg.ProviderSubject,
		arg.ProviderEmail,
	)
	var i TutorIdentity
	err := row.Scan(
		&i.TutorID,
		&i.Provider,
		&i.ProviderSubject,
		&i.ProviderEmail,
		&i.LinkedAt,
	)
	return i, err
}

const updateTutorFromProvider = `-- name: UpdateTutorFromProvider :one
UPDATE tutors
SET email = $2, display_name = $3, updated_at = now()
WHERE tutor_id = $1
RETURNING tutor_id, email, display_name, timezone, language, created_at
`

type UpdateTutorFromProviderParams struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
}

type UpdateTutorFromProviderRow struct {
	TutorID     uuid.UUID
	Email       string
	DisplayName string
	Timezone    string
	Language    string
	CreatedAt   time.Time
}

// The email copy is kept in step with Google's, which owns it. updated_at is
// what identity.tutor.profile.changed stamps; the event itself carries only
// spec 0001's five fields.
func (q *Queries) UpdateTutorFromProvider(ctx context.Context, arg UpdateTutorFromProviderParams) (UpdateTutorFromProviderRow, error) {
	row := q.db.QueryRow(ctx, updateTutorFromProvider, arg.TutorID, arg.Email, arg.DisplayName)
	var i UpdateTutorFromProviderRow
	err := row.Scan(
		&i.TutorID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const updateTutorIdentityEmail = `-- name: UpdateTutorIdentityEmail :exec
UPDATE tutor_identities
SET provider_email = $3
WHERE tutor_id = $1 AND provider = $2
`

type UpdateTutorIdentityEmailParams struct {
	TutorID       uuid.UUID
	Provider      string
	ProviderEmail string
}

func (q *Queries) UpdateTutorIdentityEmail(ctx context.Context, arg UpdateTutorIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, updateTutorIdentityEmail, arg.TutorID, arg.Provider, arg.ProviderEmail)
	return err
}
