apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: vermouth
servers: 1
agents: 0
image: rancher/k3s:v1.35.5-k3s1@sha256:2074403abe1bded11ef3dde09d457e13be8e0b64c218b1c4f8269b4565cfbc65
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: vermouth-registry
    host: 0.0.0.0
    hostPort: "5111"
    image: registry:2.8.3@sha256:a3d8aaa63ed8681a604f1dea0aa03f100d5895b6a58ace528858a7b332415373
    volumes:
      - vermouth-registry-data:/var/lib/registry
