apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: vermouth
servers: 1
agents: 0
image: rancher/k3s:v1.36.3-k3s1@sha256:d0f79175794edd9694b4a12bafc5c52ae1977369a2f7cf256264e7bd2dae0be9
options:
  k3s:
    extraArgs:
      - arg: --kubelet-arg=container-log-max-size=10Mi
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=container-log-max-files=3
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
ports:
  - port: 127.0.0.1:8080:80
    nodeFilters:
      - loadbalancer
volumes:
  - volume: vermouth-data:/var/lib/vermouth
    nodeFilters:
      - server:*
registries:
  config: |
    mirrors:
      "vermouth-registry:5000":
        endpoint:
          - "http://vermouth-registry:5000"
  create:
    name: vermouth-registry
    host: 127.0.0.1
    hostPort: "5111"
    image: registry:2.8.3@sha256:a3d8aaa63ed8681a604f1dea0aa03f100d5895b6a58ace528858a7b332415373
    volumes:
      - vermouth-registry-data:/var/lib/registry
