// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_rosters.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeRosterPeriodAt = `-- name: CloseRosterPeriodAt :one
UPDATE roster_periods
SET effective_to = $1::date,
    updated_at = $2
WHERE tutor_id = $3
  AND class_id = $4
  AND student_id = $5
  AND effective_from = $6::date
RETURNING class_id, student_id, effective_from, tutor_id, effective_to,
          created_at, updated_at
`

type CloseRosterPeriodAtParams struct {
	EffectiveTo   pgtype.Date
	UpdatedAt     time.Time
	TutorID       uuid.UUID
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
}

func (q *Queries) CloseRosterPeriodAt(ctx context.Context, arg CloseRosterPeriodAtParams) (RosterPeriod, error) {
	row := q.db.QueryRow(ctx, closeRosterPeriodAt,
		arg.EffectiveTo,
		arg.UpdatedAt,
		arg.TutorID,
		arg.ClassID,
		arg.StudentID,
		arg.EffectiveFrom,
	)
	var i RosterPeriod
	err := row.Scan(
		&i.ClassID,
		&i.StudentID,
		&i.EffectiveFrom,
		&i.TutorID,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countClassRosterAtDate = `-- name: CountClassRosterAtDate :one
SELECT count(*)::bigint
FROM roster_periods
WHERE tutor_id = $1
  AND class_id = $2
  AND effective_from <= $3::date
  AND (effective_to IS NULL OR $3::date <= effective_to)
`

type CountClassRosterAtDateParams struct {
	TutorID      uuid.UUID
	ClassID      uuid.UUID
	ResolvedDate pgtype.Date
}

func (q *Queries) CountClassRosterAtDate(ctx context.Context, arg CountClassRosterAtDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClassRosterAtDate, arg.TutorID, arg.ClassID, arg.ResolvedDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listClassRosterAtDate = `-- name: ListClassRosterAtDate :many

SELECT
    st.student_id,
    st.name,
    st.phone,
    st.removed_at,
    rp.effective_from,
    rp.effective_to
FROM roster_periods rp
JOIN students st
  ON st.tutor_id = rp.tutor_id
 AND st.student_id = rp.student_id
WHERE rp.tutor_id = $1
  AND rp.class_id = $2
  AND rp.effective_from <= $3::date
  AND (rp.effective_to IS NULL OR $3::date <= rp.effective_to)
ORDER BY lower(st.name), st.name, st.student_id
`

type ListClassRosterAtDateParams struct {
	TutorID      uuid.UUID
	ClassID      uuid.UUID
	ResolvedDate pgtype.Date
}

type ListClassRosterAtDateRow struct {
	StudentID     uuid.UUID
	Name          string
	Phone         pgtype.Text
	RemovedAt     pgtype.Timestamptz
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
}

// Dated roster reads and writes use the same inclusive date predicate in every
// statement. The class lock in the handler serialises competing deltas.
func (q *Queries) ListClassRosterAtDate(ctx context.Context, arg ListClassRosterAtDateParams) ([]ListClassRosterAtDateRow, error) {
	rows, err := q.db.Query(ctx, listClassRosterAtDate, arg.TutorID, arg.ClassID, arg.ResolvedDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassRosterAtDateRow{}
	for rows.Next() {
		var i ListClassRosterAtDateRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.Phone,
			&i.RemovedAt,
			&i.EffectiveFrom,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterPeriodsForStudents = `-- name: ListRosterPeriodsForStudents :many
SELECT class_id, student_id, effective_from, tutor_id, effective_to,
       created_at, updated_at
FROM roster_periods
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = ANY($3::uuid[])
ORDER BY student_id, effective_from
`

type ListRosterPeriodsForStudentsParams struct {
	TutorID    uuid.UUID
	ClassID    uuid.UUID
	StudentIds []uuid.UUID
}

func (q *Queries) ListRosterPeriodsForStudents(ctx context.Context, arg ListRosterPeriodsForStudentsParams) ([]RosterPeriod, error) {
	rows, err := q.db.Query(ctx, listRosterPeriodsForStudents, arg.TutorID, arg.ClassID, arg.StudentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterPeriod{}
	for rows.Next() {
		var i RosterPeriod
		if err := rows.Scan(
			&i.ClassID,
			&i.StudentID,
			&i.EffectiveFrom,
			&i.TutorID,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRosterStudents = `-- name: LockRosterStudents :many
SELECT student_id, tutor_id, name, phone, created_at, updated_at, removed_at
FROM students
WHERE tutor_id = $1
  AND student_id = ANY($2::uuid[])
ORDER BY student_id
FOR UPDATE
`

type LockRosterStudentsParams struct {
	TutorID    uuid.UUID
	StudentIds []uuid.UUID
}

func (q *Queries) LockRosterStudents(ctx context.Context, arg LockRosterStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, lockRosterStudents, arg.TutorID, arg.StudentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.StudentID,
			&i.TutorID,
			&i.Name,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
