// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	SessionID uuid.UUID
	StudentID uuid.UUID
	TutorID   uuid.UUID
	State     string
	MarkedAt  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Class struct {
	ClassID           uuid.UUID
	TutorID           uuid.UUID
	Name              string
	RateAmount        int64
	Currency          string
	RateEffectiveFrom pgtype.Date
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ArchivedAt        pgtype.Timestamptz
	Color             string
	ScheduleRevision  int64
}

type CommandReceipt struct {
	TutorID           uuid.UUID
	Operation         string
	IdempotencyKey    string
	RequestHash       []byte
	PrimaryResourceID uuid.UUID
	RelatedResourceID pgtype.UUID
	CreatedAt         time.Time
	ContextSnapshot   []byte
	ResponseSnapshot  []byte
	ResponseStatus    pgtype.Int4
}

type HandledEvent struct {
	ConsumerName string
	EventID      uuid.UUID
	HandledAt    time.Time
}

type Outbox struct {
	ID           int64
	EventID      uuid.UUID
	EventName    string
	EventVersion int32
	OccurredAt   time.Time
	TutorID      uuid.UUID
	KeyKind      string
	KeyValue     uuid.UUID
	RequestID    string
	Topic        string
	Envelope     []byte
	CreatedAt    time.Time
	PublishedAt  pgtype.Timestamptz
}

type RosterPeriod struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
	EffectiveTo   pgtype.Date
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ScheduleRule struct {
	ScheduleRuleID uuid.UUID
	TutorID        uuid.UUID
	ClassID        uuid.UUID
	Revision       int64
	ValidFrom      pgtype.Date
	ValidThrough   pgtype.Date
	TimeZone       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ReplacedAt     pgtype.Timestamptz
	EndedAt        pgtype.Timestamptz
	RetiredAt      pgtype.Timestamptz
}

type ScheduleSlot struct {
	ScheduleRuleID uuid.UUID
	TutorID        uuid.UUID
	Weekday        int16
	StartTime      pgtype.Time
	EndTime        pgtype.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Session struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	TutorID         uuid.UUID
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	ScheduleRuleID  pgtype.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CancelledAt     pgtype.Timestamptz
	OriginLocalDate pgtype.Date
	Version         int64
	MovedAt         pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
}

type Student struct {
	StudentID uuid.UUID
	TutorID   uuid.UUID
	Name      string
	Phone     pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
	RemovedAt pgtype.Timestamptz
}
