// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// CloseRosterPeriod closes the one open row for the pair, which the partial
	// unique index makes well defined: teaching.roster.left carries no
	// effective_from, so the open row is the only possible target. A second left for
	// the same pair updates nothing.
	CloseRosterPeriod(ctx context.Context, arg CloseRosterPeriodParams) error
	FindOpenRosterPeriod(ctx context.Context, arg FindOpenRosterPeriodParams) (FindOpenRosterPeriodRow, error)
	GetAttendance(ctx context.Context, arg GetAttendanceParams) (Attendance, error)
	// Locking the owned session serialises corrections, including the first mark
	// where no attendance row exists yet. The roster flag uses the same inclusive
	// coverage predicate as every home and billing read.
	GetAttendanceWriteContext(ctx context.Context, arg GetAttendanceWriteContextParams) (GetAttendanceWriteContextRow, error)
	GetCommandReceipt(ctx context.Context, arg GetCommandReceiptParams) (CommandReceipt, error)
	GetOwnedClass(ctx context.Context, arg GetOwnedClassParams) (GetOwnedClassRow, error)
	GetOwnedSession(ctx context.Context, arg GetOwnedSessionParams) (Session, error)
	GetOwnedStudent(ctx context.Context, arg GetOwnedStudentParams) (Student, error)
	InsertClass(ctx context.Context, arg InsertClassParams) (InsertClassRow, error)
	// The receipt is claimed before its business rows are inserted. A concurrent
	// loser receives no row, rolls back, then reads the committed winner.
	InsertCommandReceipt(ctx context.Context, arg InsertCommandReceiptParams) (CommandReceipt, error)
	InsertRosterPeriod(ctx context.Context, arg InsertRosterPeriodParams) (RosterPeriod, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	// Hand written SQL for teaching, compiled to typed Go by sqlc (STK-3). No ORM,
	// and no SQL assembled by string concatenation at runtime.
	//
	// Every statement here names tutor_id (INV-8, AC-4). The value comes from the
	// sub claim of the verified token and never from an input, so there is no cross
	// tutor read path and no table is reachable without the filter. Every list
	// filters on the end timestamp being empty, because nothing is ever deleted
	// (AC-11).
	InsertStudent(ctx context.Context, arg InsertStudentParams) (Student, error)
	// ListHomeSessions pages session rows before roster students are joined, so a
	// large roster cannot consume the 51 row page proof.
	ListHomeSessions(ctx context.Context, arg ListHomeSessionsParams) ([]ListHomeSessionsRow, error)
	ListHomeStudents(ctx context.Context, arg ListHomeStudentsParams) ([]ListHomeStudentsRow, error)
	// ListRosterPeriods is the whole membership history of one pair, oldest first,
	// so a rejoin reads as two periods rather than one edited row.
	ListRosterPeriods(ctx context.Context, arg ListRosterPeriodsParams) ([]ListRosterPeriodsRow, error)
	// ListSessionsForLocalDate is what the home screen asks for. The tutor's own day
	// is a date this service computed in their timezone and stored, so reading it
	// back needs no timezone arithmetic here.
	ListSessionsForLocalDate(ctx context.Context, arg ListSessionsForLocalDateParams) ([]ListSessionsForLocalDateRow, error)
	// OpenRosterPeriod starts a membership. Joining a class the student is already
	// in on the same day changes nothing, which is what makes a repeated join safe.
	OpenRosterPeriod(ctx context.Context, arg OpenRosterPeriodParams) error
	// UpsertAttendance keeps at most one row per session and student, so a
	// correction updates it in place rather than adding a second opinion, and a
	// redelivered mark lands on the same row (INV-6).
	UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error)
}

var _ Querier = (*Queries)(nil)
