// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// CloseRosterPeriod closes the one open row for the pair, which the partial
	// unique index makes well defined: teaching.roster.left carries no
	// effective_from, so the open row is the only possible target. A second left for
	// the same pair updates nothing.
	CloseRosterPeriod(ctx context.Context, arg CloseRosterPeriodParams) error
	FindOpenRosterPeriod(ctx context.Context, arg FindOpenRosterPeriodParams) (FindOpenRosterPeriodRow, error)
	GetAttendance(ctx context.Context, arg GetAttendanceParams) (Attendance, error)
	InsertClass(ctx context.Context, arg InsertClassParams) (Class, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	// Hand written SQL for teaching, compiled to typed Go by sqlc (STK-3). No ORM,
	// and no SQL assembled by string concatenation at runtime.
	//
	// Every statement here names tutor_id (INV-8, AC-4). The value comes from the
	// sub claim of the verified token and never from an input, so there is no cross
	// tutor read path and no table is reachable without the filter. Every list
	// filters on the end timestamp being empty, because nothing is ever deleted
	// (AC-11).
	InsertStudent(ctx context.Context, arg InsertStudentParams) (Student, error)
	// ListRosterPeriods is the whole membership history of one pair, oldest first,
	// so a rejoin reads as two periods rather than one edited row.
	ListRosterPeriods(ctx context.Context, arg ListRosterPeriodsParams) ([]ListRosterPeriodsRow, error)
	// ListSessionsForLocalDate is what the home screen asks for. The tutor's own day
	// is a date this service computed in their timezone and stored, so reading it
	// back needs no timezone arithmetic here.
	ListSessionsForLocalDate(ctx context.Context, arg ListSessionsForLocalDateParams) ([]ListSessionsForLocalDateRow, error)
	// OpenRosterPeriod starts a membership. Joining a class the student is already
	// in on the same day changes nothing, which is what makes a repeated join safe.
	OpenRosterPeriod(ctx context.Context, arg OpenRosterPeriodParams) error
	// UpsertAttendance keeps at most one row per session and student, so a
	// correction updates it in place rather than adding a second opinion, and a
	// redelivered mark lands on the same row (INV-6).
	UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error)
}

var _ Querier = (*Queries)(nil)
