// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_attendance.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAttendanceSheetSession = `-- name: GetAttendanceSheetSession :one

SELECT
    s.session_id,
    s.class_id,
    c.name AS class_name,
    c.color AS class_color,
    s.starts_at,
    s.ends_at,
    s.local_date,
    s.cancelled_at,
    s.superseded_at,
    c.archived_at AS class_archived_at
FROM sessions s
JOIN classes c
  ON c.tutor_id = s.tutor_id
 AND c.class_id = s.class_id
WHERE s.tutor_id = $1
  AND s.session_id = $2
`

type GetAttendanceSheetSessionParams struct {
	TutorID   uuid.UUID
	SessionID uuid.UUID
}

type GetAttendanceSheetSessionRow struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	ClassName       string
	ClassColor      string
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	CancelledAt     pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
	ClassArchivedAt pgtype.Timestamptz
}

// Whole roster attendance reads use retained student labels and never select a
// phone value. Saves lock the class and session through existing owned queries.
func (q *Queries) GetAttendanceSheetSession(ctx context.Context, arg GetAttendanceSheetSessionParams) (GetAttendanceSheetSessionRow, error) {
	row := q.db.QueryRow(ctx, getAttendanceSheetSession, arg.TutorID, arg.SessionID)
	var i GetAttendanceSheetSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ClassID,
		&i.ClassName,
		&i.ClassColor,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocalDate,
		&i.CancelledAt,
		&i.SupersededAt,
		&i.ClassArchivedAt,
	)
	return i, err
}

const listAttendanceSheetStudents = `-- name: ListAttendanceSheetStudents :many
SELECT
    st.student_id,
    st.name,
    st.removed_at,
    a.state,
    a.marked_at,
    a.updated_at AS attendance_updated_at
FROM sessions sess
JOIN roster_periods rp
  ON rp.tutor_id = sess.tutor_id
 AND rp.class_id = sess.class_id
 AND rp.effective_from <= sess.local_date
 AND (rp.effective_to IS NULL OR sess.local_date <= rp.effective_to)
JOIN students st
  ON st.tutor_id = rp.tutor_id
 AND st.student_id = rp.student_id
LEFT JOIN attendance a
  ON a.tutor_id = sess.tutor_id
 AND a.session_id = sess.session_id
 AND a.student_id = st.student_id
WHERE sess.tutor_id = $1
  AND sess.session_id = $2
ORDER BY lower(st.name), st.name, st.student_id
`

type ListAttendanceSheetStudentsParams struct {
	TutorID   uuid.UUID
	SessionID uuid.UUID
}

type ListAttendanceSheetStudentsRow struct {
	StudentID           uuid.UUID
	Name                string
	RemovedAt           pgtype.Timestamptz
	State               pgtype.Text
	MarkedAt            pgtype.Timestamptz
	AttendanceUpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListAttendanceSheetStudents(ctx context.Context, arg ListAttendanceSheetStudentsParams) ([]ListAttendanceSheetStudentsRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceSheetStudents, arg.TutorID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceSheetStudentsRow{}
	for rows.Next() {
		var i ListAttendanceSheetStudentsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.RemovedAt,
			&i.State,
			&i.MarkedAt,
			&i.AttendanceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendanceAt = `-- name: UpsertAttendanceAt :one
INSERT INTO attendance (
    session_id, student_id, tutor_id, state, marked_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $5, $5)
ON CONFLICT (session_id, student_id) DO UPDATE
SET state = excluded.state,
    marked_at = excluded.marked_at,
    updated_at = excluded.updated_at
WHERE attendance.tutor_id = excluded.tutor_id
RETURNING session_id, student_id, tutor_id, state, marked_at, created_at, updated_at
`

type UpsertAttendanceAtParams struct {
	SessionID uuid.UUID
	StudentID uuid.UUID
	TutorID   uuid.UUID
	State     string
	MarkedAt  time.Time
}

func (q *Queries) UpsertAttendanceAt(ctx context.Context, arg UpsertAttendanceAtParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, upsertAttendanceAt,
		arg.SessionID,
		arg.StudentID,
		arg.TutorID,
		arg.State,
		arg.MarkedAt,
	)
	var i Attendance
	err := row.Scan(
		&i.SessionID,
		&i.StudentID,
		&i.TutorID,
		&i.State,
		&i.MarkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
