// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_records.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveStudentRecord = `-- name: ArchiveStudentRecord :one
UPDATE students
SET removed_at = $3,
    updated_at = $3
WHERE tutor_id = $1
  AND student_id = $2
  AND removed_at IS NULL
RETURNING student_id, tutor_id, name, phone, created_at, updated_at, removed_at
`

type ArchiveStudentRecordParams struct {
	TutorID   uuid.UUID
	StudentID uuid.UUID
	RemovedAt pgtype.Timestamptz
}

func (q *Queries) ArchiveStudentRecord(ctx context.Context, arg ArchiveStudentRecordParams) (Student, error) {
	row := q.db.QueryRow(ctx, archiveStudentRecord, arg.TutorID, arg.StudentID, arg.RemovedAt)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const getActiveOwnedStudent = `-- name: GetActiveOwnedStudent :one
SELECT student_id, tutor_id, name, phone, created_at, updated_at, removed_at
FROM students
WHERE tutor_id = $1
  AND student_id = $2
  AND removed_at IS NULL
`

type GetActiveOwnedStudentParams struct {
	TutorID   uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) GetActiveOwnedStudent(ctx context.Context, arg GetActiveOwnedStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, getActiveOwnedStudent, arg.TutorID, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listActiveStudentClasses = `-- name: ListActiveStudentClasses :many
SELECT c.class_id, c.name
FROM roster_periods rp
JOIN classes c
  ON c.tutor_id = rp.tutor_id
 AND c.class_id = rp.class_id
 AND c.archived_at IS NULL
WHERE rp.tutor_id = $1
  AND rp.student_id = $2
  AND rp.effective_from <= $3::date
  AND (rp.effective_to IS NULL OR $3::date <= rp.effective_to)
ORDER BY lower(c.name), c.name, c.class_id
`

type ListActiveStudentClassesParams struct {
	TutorID   uuid.UUID
	StudentID uuid.UUID
	LocalDate pgtype.Date
}

type ListActiveStudentClassesRow struct {
	ClassID uuid.UUID
	Name    string
}

func (q *Queries) ListActiveStudentClasses(ctx context.Context, arg ListActiveStudentClassesParams) ([]ListActiveStudentClassesRow, error) {
	rows, err := q.db.Query(ctx, listActiveStudentClasses, arg.TutorID, arg.StudentID, arg.LocalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStudentClassesRow{}
	for rows.Next() {
		var i ListActiveStudentClassesRow
		if err := rows.Scan(&i.ClassID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentMemberships = `-- name: ListStudentMemberships :many
SELECT
    c.class_id,
    c.name AS class_name,
    c.color AS class_color,
    rp.effective_from,
    rp.effective_to,
    (
        c.archived_at IS NULL
        AND rp.effective_from <= $1::date
        AND (rp.effective_to IS NULL OR $1::date <= rp.effective_to)
    )::boolean AS active
FROM roster_periods rp
JOIN classes c
  ON c.tutor_id = rp.tutor_id
 AND c.class_id = rp.class_id
WHERE rp.tutor_id = $2
  AND rp.student_id = $3
ORDER BY active DESC, rp.effective_from DESC, lower(c.name), c.name, c.class_id
`

type ListStudentMembershipsParams struct {
	LocalDate pgtype.Date
	TutorID   uuid.UUID
	StudentID uuid.UUID
}

type ListStudentMembershipsRow struct {
	ClassID       uuid.UUID
	ClassName     string
	ClassColor    string
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	Active        bool
}

func (q *Queries) ListStudentMemberships(ctx context.Context, arg ListStudentMembershipsParams) ([]ListStudentMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listStudentMemberships, arg.LocalDate, arg.TutorID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentMembershipsRow{}
	for rows.Next() {
		var i ListStudentMembershipsRow
		if err := rows.Scan(
			&i.ClassID,
			&i.ClassName,
			&i.ClassColor,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many

SELECT
    st.student_id,
    st.name,
    lower(st.name) AS lower_name,
    st.phone,
    count(c.class_id)::bigint AS active_class_count,
    st.updated_at
FROM students st
LEFT JOIN roster_periods rp
  ON rp.tutor_id = st.tutor_id
 AND rp.student_id = st.student_id
 AND rp.effective_from <= $1::date
 AND (rp.effective_to IS NULL OR $1::date <= rp.effective_to)
LEFT JOIN classes c
  ON c.tutor_id = rp.tutor_id
 AND c.class_id = rp.class_id
 AND c.archived_at IS NULL
WHERE st.tutor_id = $2
  AND st.removed_at IS NULL
  AND (
      $3::text = ''
      OR strpos(lower(st.name), lower($3::text)) > 0
      OR strpos(coalesce(st.phone, ''), $3::text) > 0
  )
  AND (
      NOT $4::boolean
      OR (lower(st.name), st.name, st.student_id) > (
          $5::text,
          $6::text,
          $7::uuid
      )
  )
GROUP BY st.student_id, st.name, st.phone, st.updated_at
ORDER BY lower(st.name), st.name, st.student_id
LIMIT $8
`

type ListStudentsParams struct {
	LocalDate       pgtype.Date
	TutorID         uuid.UUID
	SearchQuery     string
	HasCursor       bool
	CursorLowerName string
	CursorName      string
	CursorStudentID uuid.UUID
	PageSize        int32
}

type ListStudentsRow struct {
	StudentID        uuid.UUID
	Name             string
	LowerName        string
	Phone            pgtype.Text
	ActiveClassCount int64
	UpdatedAt        time.Time
}

// Student record reads and writes remain inside teaching. Every statement
// includes the tutor identifier supplied by verified token claims.
func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.LocalDate,
		arg.TutorID,
		arg.SearchQuery,
		arg.HasCursor,
		arg.CursorLowerName,
		arg.CursorName,
		arg.CursorStudentID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsRow{}
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Name,
			&i.LowerName,
			&i.Phone,
			&i.ActiveClassCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveOwnedStudent = `-- name: LockActiveOwnedStudent :one
SELECT student_id, tutor_id, name, phone, created_at, updated_at, removed_at
FROM students
WHERE tutor_id = $1
  AND student_id = $2
  AND removed_at IS NULL
FOR UPDATE
`

type LockActiveOwnedStudentParams struct {
	TutorID   uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) LockActiveOwnedStudent(ctx context.Context, arg LockActiveOwnedStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, lockActiveOwnedStudent, arg.TutorID, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const updateStudentRecord = `-- name: UpdateStudentRecord :one
UPDATE students
SET name = $3,
    phone = $4,
    updated_at = $5
WHERE tutor_id = $1
  AND student_id = $2
  AND removed_at IS NULL
RETURNING student_id, tutor_id, name, phone, created_at, updated_at, removed_at
`

type UpdateStudentRecordParams struct {
	TutorID   uuid.UUID
	StudentID uuid.UUID
	Name      string
	Phone     pgtype.Text
	UpdatedAt time.Time
}

func (q *Queries) UpdateStudentRecord(ctx context.Context, arg UpdateStudentRecordParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudentRecord,
		arg.TutorID,
		arg.StudentID,
		arg.Name,
		arg.Phone,
		arg.UpdatedAt,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}
