// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teaching.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeRosterPeriod = `-- name: CloseRosterPeriod :exec
UPDATE roster_periods
SET effective_to = $4,
    updated_at   = now()
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = $3
  AND effective_to IS NULL
`

type CloseRosterPeriodParams struct {
	TutorID     uuid.UUID
	ClassID     uuid.UUID
	StudentID   uuid.UUID
	EffectiveTo pgtype.Date
}

// CloseRosterPeriod closes the one open row for the pair, which the partial
// unique index makes well defined: teaching.roster.left carries no
// effective_from, so the open row is the only possible target. A second left for
// the same pair updates nothing.
func (q *Queries) CloseRosterPeriod(ctx context.Context, arg CloseRosterPeriodParams) error {
	_, err := q.db.Exec(ctx, closeRosterPeriod,
		arg.TutorID,
		arg.ClassID,
		arg.StudentID,
		arg.EffectiveTo,
	)
	return err
}

const findOpenRosterPeriod = `-- name: FindOpenRosterPeriod :one
SELECT class_id, student_id, effective_from, tutor_id, effective_to
FROM roster_periods
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = $3
  AND effective_to IS NULL
`

type FindOpenRosterPeriodParams struct {
	TutorID   uuid.UUID
	ClassID   uuid.UUID
	StudentID uuid.UUID
}

type FindOpenRosterPeriodRow struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
	EffectiveTo   pgtype.Date
}

func (q *Queries) FindOpenRosterPeriod(ctx context.Context, arg FindOpenRosterPeriodParams) (FindOpenRosterPeriodRow, error) {
	row := q.db.QueryRow(ctx, findOpenRosterPeriod, arg.TutorID, arg.ClassID, arg.StudentID)
	var i FindOpenRosterPeriodRow
	err := row.Scan(
		&i.ClassID,
		&i.StudentID,
		&i.EffectiveFrom,
		&i.TutorID,
		&i.EffectiveTo,
	)
	return i, err
}

const getAttendance = `-- name: GetAttendance :one
SELECT session_id, student_id, tutor_id, state, marked_at, created_at, updated_at
FROM attendance
WHERE tutor_id = $1
  AND session_id = $2
  AND student_id = $3
`

type GetAttendanceParams struct {
	TutorID   uuid.UUID
	SessionID uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) GetAttendance(ctx context.Context, arg GetAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendance, arg.TutorID, arg.SessionID, arg.StudentID)
	var i Attendance
	err := row.Scan(
		&i.SessionID,
		&i.StudentID,
		&i.TutorID,
		&i.State,
		&i.MarkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttendanceWriteContext = `-- name: GetAttendanceWriteContext :one
SELECT s.session_id, s.class_id, s.local_date,
       EXISTS (
           SELECT 1
           FROM roster_periods rp
           WHERE rp.tutor_id = s.tutor_id
             AND rp.class_id = s.class_id
             AND rp.student_id = st.student_id
             AND rp.effective_from <= s.local_date
             AND (rp.effective_to IS NULL OR s.local_date <= rp.effective_to)
       )::boolean AS rostered
FROM sessions s
JOIN students st
  ON st.tutor_id = s.tutor_id
 AND st.student_id = $1
 AND st.removed_at IS NULL
WHERE s.tutor_id = $2
  AND s.session_id = $3
  AND s.cancelled_at IS NULL
FOR UPDATE
`

type GetAttendanceWriteContextParams struct {
	StudentID uuid.UUID
	TutorID   uuid.UUID
	SessionID uuid.UUID
}

type GetAttendanceWriteContextRow struct {
	SessionID uuid.UUID
	ClassID   uuid.UUID
	LocalDate pgtype.Date
	Rostered  bool
}

// Locking the owned session serialises corrections, including the first mark
// where no attendance row exists yet. The roster flag uses the same inclusive
// coverage predicate as every home and billing read.
func (q *Queries) GetAttendanceWriteContext(ctx context.Context, arg GetAttendanceWriteContextParams) (GetAttendanceWriteContextRow, error) {
	row := q.db.QueryRow(ctx, getAttendanceWriteContext, arg.StudentID, arg.TutorID, arg.SessionID)
	var i GetAttendanceWriteContextRow
	err := row.Scan(
		&i.SessionID,
		&i.ClassID,
		&i.LocalDate,
		&i.Rostered,
	)
	return i, err
}

const getCommandReceipt = `-- name: GetCommandReceipt :one
SELECT tutor_id, operation, idempotency_key, request_hash,
       primary_resource_id, related_resource_id, created_at
FROM command_receipts
WHERE tutor_id = $1
  AND operation = $2
  AND idempotency_key = $3
`

type GetCommandReceiptParams struct {
	TutorID        uuid.UUID
	Operation      string
	IdempotencyKey string
}

type GetCommandReceiptRow struct {
	TutorID           uuid.UUID
	Operation         string
	IdempotencyKey    string
	RequestHash       []byte
	PrimaryResourceID uuid.UUID
	RelatedResourceID pgtype.UUID
	CreatedAt         time.Time
}

func (q *Queries) GetCommandReceipt(ctx context.Context, arg GetCommandReceiptParams) (GetCommandReceiptRow, error) {
	row := q.db.QueryRow(ctx, getCommandReceipt, arg.TutorID, arg.Operation, arg.IdempotencyKey)
	var i GetCommandReceiptRow
	err := row.Scan(
		&i.TutorID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PrimaryResourceID,
		&i.RelatedResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnedClass = `-- name: GetOwnedClass :one
SELECT class_id, tutor_id, name, color, rate_amount, currency,
       rate_effective_from, schedule_revision, created_at, updated_at, archived_at
FROM classes
WHERE tutor_id = $1
  AND class_id = $2
`

type GetOwnedClassParams struct {
	TutorID uuid.UUID
	ClassID uuid.UUID
}

type GetOwnedClassRow struct {
	ClassID           uuid.UUID
	TutorID           uuid.UUID
	Name              string
	Color             string
	RateAmount        int64
	Currency          string
	RateEffectiveFrom pgtype.Date
	ScheduleRevision  int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ArchivedAt        pgtype.Timestamptz
}

func (q *Queries) GetOwnedClass(ctx context.Context, arg GetOwnedClassParams) (GetOwnedClassRow, error) {
	row := q.db.QueryRow(ctx, getOwnedClass, arg.TutorID, arg.ClassID)
	var i GetOwnedClassRow
	err := row.Scan(
		&i.ClassID,
		&i.TutorID,
		&i.Name,
		&i.Color,
		&i.RateAmount,
		&i.Currency,
		&i.RateEffectiveFrom,
		&i.ScheduleRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getOwnedLatestScheduleRule = `-- name: GetOwnedLatestScheduleRule :one
SELECT schedule_rule_id, tutor_id, class_id, revision, valid_from, valid_through,
       time_zone, created_at, updated_at, replaced_at, ended_at, retired_at
FROM schedule_rules
WHERE tutor_id = $1
  AND class_id = $2
ORDER BY revision DESC
LIMIT 1
`

type GetOwnedLatestScheduleRuleParams struct {
	TutorID uuid.UUID
	ClassID uuid.UUID
}

func (q *Queries) GetOwnedLatestScheduleRule(ctx context.Context, arg GetOwnedLatestScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, getOwnedLatestScheduleRule, arg.TutorID, arg.ClassID)
	var i ScheduleRule
	err := row.Scan(
		&i.ScheduleRuleID,
		&i.TutorID,
		&i.ClassID,
		&i.Revision,
		&i.ValidFrom,
		&i.ValidThrough,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplacedAt,
		&i.EndedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getOwnedSession = `-- name: GetOwnedSession :one
SELECT session_id, class_id, tutor_id, starts_at, ends_at, local_date,
       schedule_rule_id, origin_local_date, version, moved_at, superseded_at,
       created_at, updated_at, cancelled_at
FROM sessions
WHERE tutor_id = $1
  AND session_id = $2
`

type GetOwnedSessionParams struct {
	TutorID   uuid.UUID
	SessionID uuid.UUID
}

type GetOwnedSessionRow struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	TutorID         uuid.UUID
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	ScheduleRuleID  pgtype.UUID
	OriginLocalDate pgtype.Date
	Version         int64
	MovedAt         pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CancelledAt     pgtype.Timestamptz
}

func (q *Queries) GetOwnedSession(ctx context.Context, arg GetOwnedSessionParams) (GetOwnedSessionRow, error) {
	row := q.db.QueryRow(ctx, getOwnedSession, arg.TutorID, arg.SessionID)
	var i GetOwnedSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ClassID,
		&i.TutorID,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocalDate,
		&i.ScheduleRuleID,
		&i.OriginLocalDate,
		&i.Version,
		&i.MovedAt,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getOwnedStudent = `-- name: GetOwnedStudent :one
SELECT student_id, tutor_id, name, phone, created_at, updated_at, removed_at
FROM students
WHERE tutor_id = $1
  AND student_id = $2
`

type GetOwnedStudentParams struct {
	TutorID   uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) GetOwnedStudent(ctx context.Context, arg GetOwnedStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, getOwnedStudent, arg.TutorID, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const insertClass = `-- name: InsertClass :one
INSERT INTO classes (
    class_id, tutor_id, name, color, rate_amount, currency, rate_effective_from,
    schedule_revision
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING class_id, tutor_id, name, color, rate_amount, currency, rate_effective_from,
          schedule_revision, created_at, updated_at, archived_at
`

type InsertClassParams struct {
	ClassID           uuid.UUID
	TutorID           uuid.UUID
	Name              string
	Color             string
	RateAmount        int64
	Currency          string
	RateEffectiveFrom pgtype.Date
	ScheduleRevision  int64
}

type InsertClassRow struct {
	ClassID           uuid.UUID
	TutorID           uuid.UUID
	Name              string
	Color             string
	RateAmount        int64
	Currency          string
	RateEffectiveFrom pgtype.Date
	ScheduleRevision  int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ArchivedAt        pgtype.Timestamptz
}

func (q *Queries) InsertClass(ctx context.Context, arg InsertClassParams) (InsertClassRow, error) {
	row := q.db.QueryRow(ctx, insertClass,
		arg.ClassID,
		arg.TutorID,
		arg.Name,
		arg.Color,
		arg.RateAmount,
		arg.Currency,
		arg.RateEffectiveFrom,
		arg.ScheduleRevision,
	)
	var i InsertClassRow
	err := row.Scan(
		&i.ClassID,
		&i.TutorID,
		&i.Name,
		&i.Color,
		&i.RateAmount,
		&i.Currency,
		&i.RateEffectiveFrom,
		&i.ScheduleRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertCommandReceipt = `-- name: InsertCommandReceipt :one
INSERT INTO command_receipts (
    tutor_id, operation, idempotency_key, request_hash,
    primary_resource_id, related_resource_id
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tutor_id, operation, idempotency_key) DO NOTHING
RETURNING tutor_id, operation, idempotency_key, request_hash,
          primary_resource_id, related_resource_id, created_at
`

type InsertCommandReceiptParams struct {
	TutorID           uuid.UUID
	Operation         string
	IdempotencyKey    string
	RequestHash       []byte
	PrimaryResourceID uuid.UUID
	RelatedResourceID pgtype.UUID
}

type InsertCommandReceiptRow struct {
	TutorID           uuid.UUID
	Operation         string
	IdempotencyKey    string
	RequestHash       []byte
	PrimaryResourceID uuid.UUID
	RelatedResourceID pgtype.UUID
	CreatedAt         time.Time
}

// The receipt is claimed before its business rows are inserted. A concurrent
// loser receives no row, rolls back, then reads the committed winner.
func (q *Queries) InsertCommandReceipt(ctx context.Context, arg InsertCommandReceiptParams) (InsertCommandReceiptRow, error) {
	row := q.db.QueryRow(ctx, insertCommandReceipt,
		arg.TutorID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.PrimaryResourceID,
		arg.RelatedResourceID,
	)
	var i InsertCommandReceiptRow
	err := row.Scan(
		&i.TutorID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.PrimaryResourceID,
		&i.RelatedResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const insertRosterPeriod = `-- name: InsertRosterPeriod :one
INSERT INTO roster_periods (class_id, student_id, effective_from, tutor_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (class_id, student_id, effective_from) DO NOTHING
RETURNING class_id, student_id, effective_from, tutor_id, effective_to,
          created_at, updated_at
`

type InsertRosterPeriodParams struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
}

func (q *Queries) InsertRosterPeriod(ctx context.Context, arg InsertRosterPeriodParams) (RosterPeriod, error) {
	row := q.db.QueryRow(ctx, insertRosterPeriod,
		arg.ClassID,
		arg.StudentID,
		arg.EffectiveFrom,
		arg.TutorID,
	)
	var i RosterPeriod
	err := row.Scan(
		&i.ClassID,
		&i.StudentID,
		&i.EffectiveFrom,
		&i.TutorID,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScheduleRule = `-- name: InsertScheduleRule :one
INSERT INTO schedule_rules (
    schedule_rule_id, tutor_id, class_id, revision, valid_from, valid_through, time_zone
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING schedule_rule_id, tutor_id, class_id, revision, valid_from, valid_through,
          time_zone, created_at, updated_at, replaced_at, ended_at, retired_at
`

type InsertScheduleRuleParams struct {
	ScheduleRuleID uuid.UUID
	TutorID        uuid.UUID
	ClassID        uuid.UUID
	Revision       int64
	ValidFrom      pgtype.Date
	ValidThrough   pgtype.Date
	TimeZone       string
}

func (q *Queries) InsertScheduleRule(ctx context.Context, arg InsertScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, insertScheduleRule,
		arg.ScheduleRuleID,
		arg.TutorID,
		arg.ClassID,
		arg.Revision,
		arg.ValidFrom,
		arg.ValidThrough,
		arg.TimeZone,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ScheduleRuleID,
		&i.TutorID,
		&i.ClassID,
		&i.Revision,
		&i.ValidFrom,
		&i.ValidThrough,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplacedAt,
		&i.EndedAt,
		&i.RetiredAt,
	)
	return i, err
}

const insertScheduleSlot = `-- name: InsertScheduleSlot :one
INSERT INTO schedule_slots (
    schedule_rule_id, tutor_id, weekday, start_time, end_time
)
VALUES (
    $1,
    $2,
    $3,
    $4::text::time,
    $5::text::time
)
RETURNING schedule_rule_id, tutor_id, weekday,
          to_char(start_time, 'HH24:MI') AS start_time,
          to_char(end_time, 'HH24:MI') AS end_time,
          created_at, updated_at
`

type InsertScheduleSlotParams struct {
	ScheduleRuleID uuid.UUID
	TutorID        uuid.UUID
	Weekday        int16
	StartTime      string
	EndTime        string
}

type InsertScheduleSlotRow struct {
	ScheduleRuleID uuid.UUID
	TutorID        uuid.UUID
	Weekday        int16
	StartTime      string
	EndTime        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertScheduleSlot(ctx context.Context, arg InsertScheduleSlotParams) (InsertScheduleSlotRow, error) {
	row := q.db.QueryRow(ctx, insertScheduleSlot,
		arg.ScheduleRuleID,
		arg.TutorID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i InsertScheduleSlotRow
	err := row.Scan(
		&i.ScheduleRuleID,
		&i.TutorID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (
    session_id, class_id, tutor_id, starts_at, ends_at, local_date,
    schedule_rule_id, origin_local_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    coalesce($8::date, $6::date)
)
RETURNING session_id, class_id, tutor_id, starts_at, ends_at, local_date,
          schedule_rule_id, origin_local_date, version, moved_at, superseded_at,
          created_at, updated_at, cancelled_at
`

type InsertSessionParams struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	TutorID         uuid.UUID
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	ScheduleRuleID  pgtype.UUID
	OriginLocalDate pgtype.Date
}

type InsertSessionRow struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	TutorID         uuid.UUID
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	ScheduleRuleID  pgtype.UUID
	OriginLocalDate pgtype.Date
	Version         int64
	MovedAt         pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CancelledAt     pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.SessionID,
		arg.ClassID,
		arg.TutorID,
		arg.StartsAt,
		arg.EndsAt,
		arg.LocalDate,
		arg.ScheduleRuleID,
		arg.OriginLocalDate,
	)
	var i InsertSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ClassID,
		&i.TutorID,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocalDate,
		&i.ScheduleRuleID,
		&i.OriginLocalDate,
		&i.Version,
		&i.MovedAt,
		&i.SupersededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const insertStudent = `-- name: InsertStudent :one

INSERT INTO students (student_id, tutor_id, name, phone)
VALUES ($1, $2, $3, $4)
RETURNING student_id, tutor_id, name, phone, created_at, updated_at, removed_at
`

type InsertStudentParams struct {
	StudentID uuid.UUID
	TutorID   uuid.UUID
	Name      string
	Phone     pgtype.Text
}

// Hand written SQL for teaching, compiled to typed Go by sqlc (STK-3). No ORM,
// and no SQL assembled by string concatenation at runtime.
//
// Every statement here names tutor_id (INV-8, AC-4). The value comes from the
// sub claim of the verified token and never from an input, so there is no cross
// tutor read path and no table is reachable without the filter. Every list
// filters on the end timestamp being empty, because nothing is ever deleted
// (AC-11).
func (q *Queries) InsertStudent(ctx context.Context, arg InsertStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, insertStudent,
		arg.StudentID,
		arg.TutorID,
		arg.Name,
		arg.Phone,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listHomeSessions = `-- name: ListHomeSessions :many
SELECT s.session_id, s.class_id, c.name AS class_name, c.color AS class_color,
       s.starts_at, s.ends_at, s.local_date
FROM sessions s
JOIN classes c
  ON c.tutor_id = s.tutor_id
 AND c.class_id = s.class_id
WHERE s.tutor_id = $1
  AND s.local_date = $2
  AND s.cancelled_at IS NULL
  AND s.superseded_at IS NULL
  AND c.archived_at IS NULL
  AND (
      NOT $3::boolean
      OR (s.starts_at, s.session_id) >
         ($4::timestamptz, $5::uuid)
  )
ORDER BY s.starts_at, s.session_id
LIMIT $6
`

type ListHomeSessionsParams struct {
	TutorID         uuid.UUID
	LocalDate       pgtype.Date
	HasCursor       bool
	CursorStartsAt  time.Time
	CursorSessionID uuid.UUID
	PageSize        int32
}

type ListHomeSessionsRow struct {
	SessionID  uuid.UUID
	ClassID    uuid.UUID
	ClassName  string
	ClassColor string
	StartsAt   time.Time
	EndsAt     time.Time
	LocalDate  pgtype.Date
}

// ListHomeSessions pages session rows before roster students are joined, so a
// large roster cannot consume the 51 row page proof.
func (q *Queries) ListHomeSessions(ctx context.Context, arg ListHomeSessionsParams) ([]ListHomeSessionsRow, error) {
	rows, err := q.db.Query(ctx, listHomeSessions,
		arg.TutorID,
		arg.LocalDate,
		arg.HasCursor,
		arg.CursorStartsAt,
		arg.CursorSessionID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeSessionsRow{}
	for rows.Next() {
		var i ListHomeSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClassID,
			&i.ClassName,
			&i.ClassColor,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeStudents = `-- name: ListHomeStudents :many
SELECT rp.class_id, sess.session_id, st.student_id, st.name,
       a.state AS attendance_state, a.marked_at
FROM sessions sess
JOIN roster_periods rp
  ON rp.tutor_id = sess.tutor_id
 AND rp.class_id = sess.class_id
 AND rp.effective_from <= sess.local_date
 AND (rp.effective_to IS NULL OR sess.local_date <= rp.effective_to)
JOIN students st
  ON st.tutor_id = rp.tutor_id
 AND st.student_id = rp.student_id
 AND st.removed_at IS NULL
LEFT JOIN attendance a
  ON a.tutor_id = sess.tutor_id
 AND a.session_id = sess.session_id
 AND a.student_id = st.student_id
WHERE sess.tutor_id = $1
  AND sess.session_id = ANY($2::uuid[])
ORDER BY sess.starts_at, sess.session_id, st.name, st.student_id
`

type ListHomeStudentsParams struct {
	TutorID    uuid.UUID
	SessionIds []uuid.UUID
}

type ListHomeStudentsRow struct {
	ClassID         uuid.UUID
	SessionID       uuid.UUID
	StudentID       uuid.UUID
	Name            string
	AttendanceState pgtype.Text
	MarkedAt        pgtype.Timestamptz
}

func (q *Queries) ListHomeStudents(ctx context.Context, arg ListHomeStudentsParams) ([]ListHomeStudentsRow, error) {
	rows, err := q.db.Query(ctx, listHomeStudents, arg.TutorID, arg.SessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeStudentsRow{}
	for rows.Next() {
		var i ListHomeStudentsRow
		if err := rows.Scan(
			&i.ClassID,
			&i.SessionID,
			&i.StudentID,
			&i.Name,
			&i.AttendanceState,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedClassSessions = `-- name: ListOwnedClassSessions :many
SELECT session_id, class_id, tutor_id, starts_at, ends_at, local_date,
       schedule_rule_id, origin_local_date, version, moved_at, superseded_at,
       created_at, updated_at, cancelled_at
FROM sessions
WHERE tutor_id = $1
  AND class_id = $2
ORDER BY starts_at, session_id
`

type ListOwnedClassSessionsParams struct {
	TutorID uuid.UUID
	ClassID uuid.UUID
}

type ListOwnedClassSessionsRow struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	TutorID         uuid.UUID
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	ScheduleRuleID  pgtype.UUID
	OriginLocalDate pgtype.Date
	Version         int64
	MovedAt         pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CancelledAt     pgtype.Timestamptz
}

func (q *Queries) ListOwnedClassSessions(ctx context.Context, arg ListOwnedClassSessionsParams) ([]ListOwnedClassSessionsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedClassSessions, arg.TutorID, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedClassSessionsRow{}
	for rows.Next() {
		var i ListOwnedClassSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClassID,
			&i.TutorID,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocalDate,
			&i.ScheduleRuleID,
			&i.OriginLocalDate,
			&i.Version,
			&i.MovedAt,
			&i.SupersededAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterPeriods = `-- name: ListRosterPeriods :many
SELECT class_id, student_id, effective_from, tutor_id, effective_to
FROM roster_periods
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = $3
ORDER BY effective_from
`

type ListRosterPeriodsParams struct {
	TutorID   uuid.UUID
	ClassID   uuid.UUID
	StudentID uuid.UUID
}

type ListRosterPeriodsRow struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
	EffectiveTo   pgtype.Date
}

// ListRosterPeriods is the whole membership history of one pair, oldest first,
// so a rejoin reads as two periods rather than one edited row.
func (q *Queries) ListRosterPeriods(ctx context.Context, arg ListRosterPeriodsParams) ([]ListRosterPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listRosterPeriods, arg.TutorID, arg.ClassID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterPeriodsRow{}
	for rows.Next() {
		var i ListRosterPeriodsRow
		if err := rows.Scan(
			&i.ClassID,
			&i.StudentID,
			&i.EffectiveFrom,
			&i.TutorID,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleClasses = `-- name: ListScheduleClasses :many
SELECT class_id, name, color, schedule_revision, archived_at
FROM classes
WHERE tutor_id = $1
  AND archived_at IS NULL
ORDER BY name, class_id
`

type ListScheduleClassesRow struct {
	ClassID          uuid.UUID
	Name             string
	Color            string
	ScheduleRevision int64
	ArchivedAt       pgtype.Timestamptz
}

func (q *Queries) ListScheduleClasses(ctx context.Context, tutorID uuid.UUID) ([]ListScheduleClassesRow, error) {
	rows, err := q.db.Query(ctx, listScheduleClasses, tutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleClassesRow{}
	for rows.Next() {
		var i ListScheduleClassesRow
		if err := rows.Scan(
			&i.ClassID,
			&i.Name,
			&i.Color,
			&i.ScheduleRevision,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRules = `-- name: ListScheduleRules :many
SELECT schedule_rule_id, class_id, revision, valid_from, valid_through, time_zone,
       replaced_at, ended_at, retired_at
FROM schedule_rules
WHERE tutor_id = $1
  AND valid_from <= $2
  AND valid_through >= $3
  AND (
      NOT $4::boolean
      OR class_id = ANY($5::uuid[])
  )
ORDER BY class_id, revision
`

type ListScheduleRulesParams struct {
	TutorID        uuid.UUID
	ThroughDate    pgtype.Date
	FromDate       pgtype.Date
	HasClassFilter bool
	ClassIds       []uuid.UUID
}

type ListScheduleRulesRow struct {
	ScheduleRuleID uuid.UUID
	ClassID        uuid.UUID
	Revision       int64
	ValidFrom      pgtype.Date
	ValidThrough   pgtype.Date
	TimeZone       string
	ReplacedAt     pgtype.Timestamptz
	EndedAt        pgtype.Timestamptz
	RetiredAt      pgtype.Timestamptz
}

func (q *Queries) ListScheduleRules(ctx context.Context, arg ListScheduleRulesParams) ([]ListScheduleRulesRow, error) {
	rows, err := q.db.Query(ctx, listScheduleRules,
		arg.TutorID,
		arg.ThroughDate,
		arg.FromDate,
		arg.HasClassFilter,
		arg.ClassIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRulesRow{}
	for rows.Next() {
		var i ListScheduleRulesRow
		if err := rows.Scan(
			&i.ScheduleRuleID,
			&i.ClassID,
			&i.Revision,
			&i.ValidFrom,
			&i.ValidThrough,
			&i.TimeZone,
			&i.ReplacedAt,
			&i.EndedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleSessions = `-- name: ListScheduleSessions :many
SELECT s.session_id, s.class_id, c.name AS class_name, c.color AS class_color,
       c.archived_at, s.starts_at, s.ends_at, s.local_date, s.origin_local_date,
       s.schedule_rule_id, r.time_zone AS source_time_zone, s.version,
       s.moved_at, s.cancelled_at, s.superseded_at, s.updated_at
FROM sessions s
JOIN classes c
  ON c.tutor_id = s.tutor_id
 AND c.class_id = s.class_id
LEFT JOIN schedule_rules r
  ON r.tutor_id = s.tutor_id
 AND r.class_id = s.class_id
 AND r.schedule_rule_id = s.schedule_rule_id
WHERE s.tutor_id = $1
  AND s.starts_at >= $2
  AND s.starts_at < $3
  AND s.superseded_at IS NULL
  AND (
      NOT $4::boolean
      OR s.class_id = ANY($5::uuid[])
  )
ORDER BY s.starts_at, s.session_id
`

type ListScheduleSessionsParams struct {
	TutorID        uuid.UUID
	FromInstant    time.Time
	ThroughInstant time.Time
	HasClassFilter bool
	ClassIds       []uuid.UUID
}

type ListScheduleSessionsRow struct {
	SessionID       uuid.UUID
	ClassID         uuid.UUID
	ClassName       string
	ClassColor      string
	ArchivedAt      pgtype.Timestamptz
	StartsAt        time.Time
	EndsAt          time.Time
	LocalDate       pgtype.Date
	OriginLocalDate pgtype.Date
	ScheduleRuleID  pgtype.UUID
	SourceTimeZone  pgtype.Text
	Version         int64
	MovedAt         pgtype.Timestamptz
	CancelledAt     pgtype.Timestamptz
	SupersededAt    pgtype.Timestamptz
	UpdatedAt       time.Time
}

func (q *Queries) ListScheduleSessions(ctx context.Context, arg ListScheduleSessionsParams) ([]ListScheduleSessionsRow, error) {
	rows, err := q.db.Query(ctx, listScheduleSessions,
		arg.TutorID,
		arg.FromInstant,
		arg.ThroughInstant,
		arg.HasClassFilter,
		arg.ClassIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleSessionsRow{}
	for rows.Next() {
		var i ListScheduleSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClassID,
			&i.ClassName,
			&i.ClassColor,
			&i.ArchivedAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocalDate,
			&i.OriginLocalDate,
			&i.ScheduleRuleID,
			&i.SourceTimeZone,
			&i.Version,
			&i.MovedAt,
			&i.CancelledAt,
			&i.SupersededAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleSlots = `-- name: ListScheduleSlots :many
SELECT schedule_rule_id, weekday,
       to_char(start_time, 'HH24:MI') AS start_time,
       to_char(end_time, 'HH24:MI') AS end_time
FROM schedule_slots
WHERE tutor_id = $1
  AND schedule_rule_id = ANY($2::uuid[])
ORDER BY schedule_rule_id, weekday
`

type ListScheduleSlotsParams struct {
	TutorID         uuid.UUID
	ScheduleRuleIds []uuid.UUID
}

type ListScheduleSlotsRow struct {
	ScheduleRuleID uuid.UUID
	Weekday        int16
	StartTime      string
	EndTime        string
}

func (q *Queries) ListScheduleSlots(ctx context.Context, arg ListScheduleSlotsParams) ([]ListScheduleSlotsRow, error) {
	rows, err := q.db.Query(ctx, listScheduleSlots, arg.TutorID, arg.ScheduleRuleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleSlotsRow{}
	for rows.Next() {
		var i ListScheduleSlotsRow
		if err := rows.Scan(
			&i.ScheduleRuleID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionConflicts = `-- name: ListSessionConflicts :many
SELECT left_session.tutor_id,
       left_session.session_id AS first_session_id,
       left_session.class_id AS first_class_id,
       left_session.starts_at AS first_starts_at,
       left_session.ends_at AS first_ends_at,
       right_session.session_id AS second_session_id,
       right_session.class_id AS second_class_id,
       right_session.starts_at AS second_starts_at,
       right_session.ends_at AS second_ends_at
FROM sessions left_session
JOIN sessions right_session
  ON right_session.tutor_id = left_session.tutor_id
 AND right_session.session_id > left_session.session_id
 AND tstzrange(right_session.starts_at, right_session.ends_at, '[)')
     && tstzrange(left_session.starts_at, left_session.ends_at, '[)')
WHERE left_session.cancelled_at IS NULL
  AND left_session.superseded_at IS NULL
  AND right_session.cancelled_at IS NULL
  AND right_session.superseded_at IS NULL
ORDER BY left_session.tutor_id, left_session.starts_at, left_session.session_id,
         right_session.session_id
`

type ListSessionConflictsRow struct {
	TutorID         uuid.UUID
	FirstSessionID  uuid.UUID
	FirstClassID    uuid.UUID
	FirstStartsAt   time.Time
	FirstEndsAt     time.Time
	SecondSessionID uuid.UUID
	SecondClassID   uuid.UUID
	SecondStartsAt  time.Time
	SecondEndsAt    time.Time
}

// ListSessionConflicts is the read only upgrade report. Each conflicting pair
// appears once in stable tutor, time, and identifier order.
func (q *Queries) ListSessionConflicts(ctx context.Context) ([]ListSessionConflictsRow, error) {
	rows, err := q.db.Query(ctx, listSessionConflicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionConflictsRow{}
	for rows.Next() {
		var i ListSessionConflictsRow
		if err := rows.Scan(
			&i.TutorID,
			&i.FirstSessionID,
			&i.FirstClassID,
			&i.FirstStartsAt,
			&i.FirstEndsAt,
			&i.SecondSessionID,
			&i.SecondClassID,
			&i.SecondStartsAt,
			&i.SecondEndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForLocalDate = `-- name: ListSessionsForLocalDate :many
SELECT session_id, class_id, tutor_id, starts_at, ends_at, local_date
FROM sessions
WHERE tutor_id = $1
  AND local_date = $2
  AND cancelled_at IS NULL
  AND superseded_at IS NULL
ORDER BY starts_at, session_id
`

type ListSessionsForLocalDateParams struct {
	TutorID   uuid.UUID
	LocalDate pgtype.Date
}

type ListSessionsForLocalDateRow struct {
	SessionID uuid.UUID
	ClassID   uuid.UUID
	TutorID   uuid.UUID
	StartsAt  time.Time
	EndsAt    time.Time
	LocalDate pgtype.Date
}

// ListSessionsForLocalDate is what the home screen asks for. The tutor's own day
// is a date this service computed in their timezone and stored, so reading it
// back needs no timezone arithmetic here.
func (q *Queries) ListSessionsForLocalDate(ctx context.Context, arg ListSessionsForLocalDateParams) ([]ListSessionsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForLocalDate, arg.TutorID, arg.LocalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForLocalDateRow{}
	for rows.Next() {
		var i ListSessionsForLocalDateRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClassID,
			&i.TutorID,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openRosterPeriod = `-- name: OpenRosterPeriod :exec
INSERT INTO roster_periods (class_id, student_id, effective_from, tutor_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (class_id, student_id, effective_from) DO NOTHING
`

type OpenRosterPeriodParams struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
}

// OpenRosterPeriod starts a membership. Joining a class the student is already
// in on the same day changes nothing, which is what makes a repeated join safe.
func (q *Queries) OpenRosterPeriod(ctx context.Context, arg OpenRosterPeriodParams) error {
	_, err := q.db.Exec(ctx, openRosterPeriod,
		arg.ClassID,
		arg.StudentID,
		arg.EffectiveFrom,
		arg.TutorID,
	)
	return err
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance (session_id, student_id, tutor_id, state, marked_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, student_id) DO UPDATE
SET state      = excluded.state,
    marked_at  = excluded.marked_at,
    updated_at = now()
WHERE attendance.tutor_id = excluded.tutor_id
RETURNING session_id, student_id, tutor_id, state, marked_at, created_at, updated_at
`

type UpsertAttendanceParams struct {
	SessionID uuid.UUID
	StudentID uuid.UUID
	TutorID   uuid.UUID
	State     string
	MarkedAt  time.Time
}

// UpsertAttendance keeps at most one row per session and student, so a
// correction updates it in place rather than adding a second opinion, and a
// redelivered mark lands on the same row (INV-6).
func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.SessionID,
		arg.StudentID,
		arg.TutorID,
		arg.State,
		arg.MarkedAt,
	)
	var i Attendance
	err := row.Scan(
		&i.SessionID,
		&i.StudentID,
		&i.TutorID,
		&i.State,
		&i.MarkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
