// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teaching.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeRosterPeriod = `-- name: CloseRosterPeriod :exec
UPDATE roster_periods
SET effective_to = $4,
    updated_at   = now()
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = $3
  AND effective_to IS NULL
`

type CloseRosterPeriodParams struct {
	TutorID     uuid.UUID
	ClassID     uuid.UUID
	StudentID   uuid.UUID
	EffectiveTo pgtype.Date
}

// CloseRosterPeriod closes the one open row for the pair, which the partial
// unique index makes well defined: teaching.roster.left carries no
// effective_from, so the open row is the only possible target. A second left for
// the same pair updates nothing.
func (q *Queries) CloseRosterPeriod(ctx context.Context, arg CloseRosterPeriodParams) error {
	_, err := q.db.Exec(ctx, closeRosterPeriod,
		arg.TutorID,
		arg.ClassID,
		arg.StudentID,
		arg.EffectiveTo,
	)
	return err
}

const findOpenRosterPeriod = `-- name: FindOpenRosterPeriod :one
SELECT class_id, student_id, effective_from, tutor_id, effective_to
FROM roster_periods
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = $3
  AND effective_to IS NULL
`

type FindOpenRosterPeriodParams struct {
	TutorID   uuid.UUID
	ClassID   uuid.UUID
	StudentID uuid.UUID
}

type FindOpenRosterPeriodRow struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
	EffectiveTo   pgtype.Date
}

func (q *Queries) FindOpenRosterPeriod(ctx context.Context, arg FindOpenRosterPeriodParams) (FindOpenRosterPeriodRow, error) {
	row := q.db.QueryRow(ctx, findOpenRosterPeriod, arg.TutorID, arg.ClassID, arg.StudentID)
	var i FindOpenRosterPeriodRow
	err := row.Scan(
		&i.ClassID,
		&i.StudentID,
		&i.EffectiveFrom,
		&i.TutorID,
		&i.EffectiveTo,
	)
	return i, err
}

const getAttendance = `-- name: GetAttendance :one
SELECT session_id, student_id, tutor_id, state, marked_at, created_at, updated_at
FROM attendance
WHERE tutor_id = $1
  AND session_id = $2
  AND student_id = $3
`

type GetAttendanceParams struct {
	TutorID   uuid.UUID
	SessionID uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) GetAttendance(ctx context.Context, arg GetAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, getAttendance, arg.TutorID, arg.SessionID, arg.StudentID)
	var i Attendance
	err := row.Scan(
		&i.SessionID,
		&i.StudentID,
		&i.TutorID,
		&i.State,
		&i.MarkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClass = `-- name: InsertClass :one
INSERT INTO classes (class_id, tutor_id, name, rate_amount, currency, rate_effective_from)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING class_id, tutor_id, name, rate_amount, currency, rate_effective_from,
          created_at, updated_at, archived_at
`

type InsertClassParams struct {
	ClassID           uuid.UUID
	TutorID           uuid.UUID
	Name              string
	RateAmount        int64
	Currency          string
	RateEffectiveFrom pgtype.Date
}

func (q *Queries) InsertClass(ctx context.Context, arg InsertClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, insertClass,
		arg.ClassID,
		arg.TutorID,
		arg.Name,
		arg.RateAmount,
		arg.Currency,
		arg.RateEffectiveFrom,
	)
	var i Class
	err := row.Scan(
		&i.ClassID,
		&i.TutorID,
		&i.Name,
		&i.RateAmount,
		&i.Currency,
		&i.RateEffectiveFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (session_id, class_id, tutor_id, starts_at, ends_at, local_date, schedule_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING session_id, class_id, tutor_id, starts_at, ends_at, local_date,
          schedule_rule_id, created_at, updated_at, cancelled_at
`

type InsertSessionParams struct {
	SessionID      uuid.UUID
	ClassID        uuid.UUID
	TutorID        uuid.UUID
	StartsAt       time.Time
	EndsAt         time.Time
	LocalDate      pgtype.Date
	ScheduleRuleID pgtype.UUID
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.SessionID,
		arg.ClassID,
		arg.TutorID,
		arg.StartsAt,
		arg.EndsAt,
		arg.LocalDate,
		arg.ScheduleRuleID,
	)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.ClassID,
		&i.TutorID,
		&i.StartsAt,
		&i.EndsAt,
		&i.LocalDate,
		&i.ScheduleRuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const insertStudent = `-- name: InsertStudent :one

INSERT INTO students (student_id, tutor_id, name, phone)
VALUES ($1, $2, $3, $4)
RETURNING student_id, tutor_id, name, phone, created_at, updated_at, removed_at
`

type InsertStudentParams struct {
	StudentID uuid.UUID
	TutorID   uuid.UUID
	Name      string
	Phone     pgtype.Text
}

// Hand written SQL for teaching, compiled to typed Go by sqlc (STK-3). No ORM,
// and no SQL assembled by string concatenation at runtime.
//
// Every statement here names tutor_id (INV-8, AC-4). The value comes from the
// sub claim of the verified token and never from an input, so there is no cross
// tutor read path and no table is reachable without the filter. Every list
// filters on the end timestamp being empty, because nothing is ever deleted
// (AC-11).
func (q *Queries) InsertStudent(ctx context.Context, arg InsertStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, insertStudent,
		arg.StudentID,
		arg.TutorID,
		arg.Name,
		arg.Phone,
	)
	var i Student
	err := row.Scan(
		&i.StudentID,
		&i.TutorID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listRosterPeriods = `-- name: ListRosterPeriods :many
SELECT class_id, student_id, effective_from, tutor_id, effective_to
FROM roster_periods
WHERE tutor_id = $1
  AND class_id = $2
  AND student_id = $3
ORDER BY effective_from
`

type ListRosterPeriodsParams struct {
	TutorID   uuid.UUID
	ClassID   uuid.UUID
	StudentID uuid.UUID
}

type ListRosterPeriodsRow struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
	EffectiveTo   pgtype.Date
}

// ListRosterPeriods is the whole membership history of one pair, oldest first,
// so a rejoin reads as two periods rather than one edited row.
func (q *Queries) ListRosterPeriods(ctx context.Context, arg ListRosterPeriodsParams) ([]ListRosterPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listRosterPeriods, arg.TutorID, arg.ClassID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterPeriodsRow{}
	for rows.Next() {
		var i ListRosterPeriodsRow
		if err := rows.Scan(
			&i.ClassID,
			&i.StudentID,
			&i.EffectiveFrom,
			&i.TutorID,
			&i.EffectiveTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForLocalDate = `-- name: ListSessionsForLocalDate :many
SELECT session_id, class_id, tutor_id, starts_at, ends_at, local_date
FROM sessions
WHERE tutor_id = $1
  AND local_date = $2
  AND cancelled_at IS NULL
ORDER BY starts_at, session_id
`

type ListSessionsForLocalDateParams struct {
	TutorID   uuid.UUID
	LocalDate pgtype.Date
}

type ListSessionsForLocalDateRow struct {
	SessionID uuid.UUID
	ClassID   uuid.UUID
	TutorID   uuid.UUID
	StartsAt  time.Time
	EndsAt    time.Time
	LocalDate pgtype.Date
}

// ListSessionsForLocalDate is what the home screen asks for. The tutor's own day
// is a date this service computed in their timezone and stored, so reading it
// back needs no timezone arithmetic here.
func (q *Queries) ListSessionsForLocalDate(ctx context.Context, arg ListSessionsForLocalDateParams) ([]ListSessionsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForLocalDate, arg.TutorID, arg.LocalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForLocalDateRow{}
	for rows.Next() {
		var i ListSessionsForLocalDateRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClassID,
			&i.TutorID,
			&i.StartsAt,
			&i.EndsAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openRosterPeriod = `-- name: OpenRosterPeriod :exec
INSERT INTO roster_periods (class_id, student_id, effective_from, tutor_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (class_id, student_id, effective_from) DO NOTHING
`

type OpenRosterPeriodParams struct {
	ClassID       uuid.UUID
	StudentID     uuid.UUID
	EffectiveFrom pgtype.Date
	TutorID       uuid.UUID
}

// OpenRosterPeriod starts a membership. Joining a class the student is already
// in on the same day changes nothing, which is what makes a repeated join safe.
func (q *Queries) OpenRosterPeriod(ctx context.Context, arg OpenRosterPeriodParams) error {
	_, err := q.db.Exec(ctx, openRosterPeriod,
		arg.ClassID,
		arg.StudentID,
		arg.EffectiveFrom,
		arg.TutorID,
	)
	return err
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance (session_id, student_id, tutor_id, state, marked_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, student_id) DO UPDATE
SET state      = excluded.state,
    marked_at  = excluded.marked_at,
    updated_at = now()
WHERE attendance.tutor_id = excluded.tutor_id
RETURNING session_id, student_id, tutor_id, state, marked_at, created_at, updated_at
`

type UpsertAttendanceParams struct {
	SessionID uuid.UUID
	StudentID uuid.UUID
	TutorID   uuid.UUID
	State     string
	MarkedAt  time.Time
}

// UpsertAttendance keeps at most one row per session and student, so a
// correction updates it in place rather than adding a second opinion, and a
// redelivered mark lands on the same row (INV-6).
func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (Attendance, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.SessionID,
		arg.StudentID,
		arg.TutorID,
		arg.State,
		arg.MarkedAt,
	)
	var i Attendance
	err := row.Scan(
		&i.SessionID,
		&i.StudentID,
		&i.TutorID,
		&i.State,
		&i.MarkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
